// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AcknowledgeInspectionEp } from '../src/api/acknowledgeInspection';
import type { default as _AddRequestMessageEp } from '../src/api/addRequestMessage';
import type { default as _AddVendorWorkOrderMessageEp } from '../src/api/addVendorWorkOrderMessage';
import type { default as _CancelRequestEp } from '../src/api/cancelRequest';
import type { default as _ConfirmApplicationFeePaymentEp } from '../src/api/confirmApplicationFeePayment';
import type { default as _ConfirmRentPaymentEp } from '../src/api/confirmRentPayment';
import type { default as _CreateApplicationFeePaymentEp } from '../src/api/createApplicationFeePayment';
import type { default as _CreateInquiryEp } from '../src/api/createInquiry';
import type { default as _CreateMaintenanceRequestEp } from '../src/api/createMaintenanceRequest';
import type { default as _CreateRentPaymentEp } from '../src/api/createRentPayment';
import type { default as _GetAccountProfileEp } from '../src/api/getAccountProfile';
import type { default as _GetMyApplicationEp } from '../src/api/getMyApplication';
import type { default as _GetOwnerOverviewEp } from '../src/api/getOwnerOverview';
import type { default as _GetOwnerPropertyEp } from '../src/api/getOwnerProperty';
import type { default as _GetOwnerStatementEp } from '../src/api/getOwnerStatement';
import type { default as _GetOwnerStatementPdfEp } from '../src/api/getOwnerStatementPdf';
import type { default as _GetPaymentReceiptEp } from '../src/api/getPaymentReceipt';
import type { default as _GetPortalEp } from '../src/api/getPortal';
import type { default as _GetPortalMeEp } from '../src/api/getPortalMe';
import type { default as _GetPublicListingEp } from '../src/api/getPublicListing';
import type { default as _GetResidentHomeEp } from '../src/api/getResidentHome';
import type { default as _GetResidentLeaseEp } from '../src/api/getResidentLease';
import type { default as _GetResidentRequestEp } from '../src/api/getResidentRequest';
import type { default as _GetVendorProfileEp } from '../src/api/getVendorProfile';
import type { default as _GetVendorWorkOrderEp } from '../src/api/getVendorWorkOrder';
import type { default as _ListMyApplicationsEp } from '../src/api/listMyApplications';
import type { default as _ListOwnerApprovalsEp } from '../src/api/listOwnerApprovals';
import type { default as _ListOwnerDocumentsEp } from '../src/api/listOwnerDocuments';
import type { default as _ListOwnerMessagesEp } from '../src/api/listOwnerMessages';
import type { default as _ListPublicListingsEp } from '../src/api/listPublicListings';
import type { default as _ListResidentDocumentsEp } from '../src/api/listResidentDocuments';
import type { default as _ListResidentLedgerEp } from '../src/api/listResidentLedger';
import type { default as _ListResidentMessagesEp } from '../src/api/listResidentMessages';
import type { default as _ListResidentRequestsEp } from '../src/api/listResidentRequests';
import type { default as _ListVendorBillsEp } from '../src/api/listVendorBills';
import type { default as _ListVendorWorkOrdersEp } from '../src/api/listVendorWorkOrders';
import type { default as _MarkOwnerMessagesReadEp } from '../src/api/markOwnerMessagesRead';
import type { default as _MarkResidentMessagesReadEp } from '../src/api/markResidentMessagesRead';
import type { default as _NotifyOfficePaidEp } from '../src/api/notifyOfficePaid';
import type { default as _RateRequestEp } from '../src/api/rateRequest';
import type { default as _RespondToApprovalEp } from '../src/api/respondToApproval';
import type { default as _RespondToRenewalEp } from '../src/api/respondToRenewal';
import type { default as _SaveApplicationDraftEp } from '../src/api/saveApplicationDraft';
import type { default as _SendApplicationMessageEp } from '../src/api/sendApplicationMessage';
import type { default as _SendOwnerMessageEp } from '../src/api/sendOwnerMessage';
import type { default as _SendResidentMessageEp } from '../src/api/sendResidentMessage';
import type { default as _SettleOnlinePaymentsEp } from '../src/api/settleOnlinePayments';
import type { default as _SignLeaseEp } from '../src/api/signLease';
import type { default as _SubmitApplicationEp } from '../src/api/submitApplication';
import type { default as _SubmitNoticeEp } from '../src/api/submitNotice';
import type { default as _SubmitVendorInvoiceEp } from '../src/api/submitVendorInvoice';
import type { default as _UpdateAccountProfileEp } from '../src/api/updateAccountProfile';
import type { default as _UpdateVendorProfileEp } from '../src/api/updateVendorProfile';
import type { default as _UpdateVendorWorkOrderEp } from '../src/api/updateVendorWorkOrder';
import type { default as _UploadResidentDocumentEp } from '../src/api/uploadResidentDocument';
import type { default as _UploadVendorDocumentEp } from '../src/api/uploadVendorDocument';
import type { default as _WithdrawApplicationEp } from '../src/api/withdrawApplication';

type _AcknowledgeInspectionCfg = typeof _AcknowledgeInspectionEp;
export type AcknowledgeInspectionInputType = NonNullable<_AcknowledgeInspectionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AcknowledgeInspectionCfg['execute']>[0]['input'];
export type AcknowledgeInspectionOutputType = Awaited<ReturnType<_AcknowledgeInspectionCfg['execute']>>;
export const acknowledgeInspection = createCaller<AcknowledgeInspectionInputType, AcknowledgeInspectionOutputType>('acknowledgeInspection');

type _AddRequestMessageCfg = typeof _AddRequestMessageEp;
export type AddRequestMessageInputType = NonNullable<_AddRequestMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AddRequestMessageCfg['execute']>[0]['input'];
export type AddRequestMessageOutputType = Awaited<ReturnType<_AddRequestMessageCfg['execute']>>;
export const addRequestMessage = createCaller<AddRequestMessageInputType, AddRequestMessageOutputType>('addRequestMessage');

type _AddVendorWorkOrderMessageCfg = typeof _AddVendorWorkOrderMessageEp;
export type AddVendorWorkOrderMessageInputType = NonNullable<_AddVendorWorkOrderMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AddVendorWorkOrderMessageCfg['execute']>[0]['input'];
export type AddVendorWorkOrderMessageOutputType = Awaited<ReturnType<_AddVendorWorkOrderMessageCfg['execute']>>;
export const addVendorWorkOrderMessage = createCaller<AddVendorWorkOrderMessageInputType, AddVendorWorkOrderMessageOutputType>('addVendorWorkOrderMessage');

type _CancelRequestCfg = typeof _CancelRequestEp;
export type CancelRequestInputType = NonNullable<_CancelRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CancelRequestCfg['execute']>[0]['input'];
export type CancelRequestOutputType = Awaited<ReturnType<_CancelRequestCfg['execute']>>;
export const cancelRequest = createCaller<CancelRequestInputType, CancelRequestOutputType>('cancelRequest');

type _ConfirmApplicationFeePaymentCfg = typeof _ConfirmApplicationFeePaymentEp;
export type ConfirmApplicationFeePaymentInputType = NonNullable<_ConfirmApplicationFeePaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ConfirmApplicationFeePaymentCfg['execute']>[0]['input'];
export type ConfirmApplicationFeePaymentOutputType = Awaited<ReturnType<_ConfirmApplicationFeePaymentCfg['execute']>>;
export const confirmApplicationFeePayment = createCaller<ConfirmApplicationFeePaymentInputType, ConfirmApplicationFeePaymentOutputType>('confirmApplicationFeePayment');

type _ConfirmRentPaymentCfg = typeof _ConfirmRentPaymentEp;
export type ConfirmRentPaymentInputType = NonNullable<_ConfirmRentPaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ConfirmRentPaymentCfg['execute']>[0]['input'];
export type ConfirmRentPaymentOutputType = Awaited<ReturnType<_ConfirmRentPaymentCfg['execute']>>;
export const confirmRentPayment = createCaller<ConfirmRentPaymentInputType, ConfirmRentPaymentOutputType>('confirmRentPayment');

type _CreateApplicationFeePaymentCfg = typeof _CreateApplicationFeePaymentEp;
export type CreateApplicationFeePaymentInputType = NonNullable<_CreateApplicationFeePaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateApplicationFeePaymentCfg['execute']>[0]['input'];
export type CreateApplicationFeePaymentOutputType = Awaited<ReturnType<_CreateApplicationFeePaymentCfg['execute']>>;
export const createApplicationFeePayment = createCaller<CreateApplicationFeePaymentInputType, CreateApplicationFeePaymentOutputType>('createApplicationFeePayment');

type _CreateInquiryCfg = typeof _CreateInquiryEp;
export type CreateInquiryInputType = NonNullable<_CreateInquiryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateInquiryCfg['execute']>[0]['input'];
export type CreateInquiryOutputType = Awaited<ReturnType<_CreateInquiryCfg['execute']>>;
export const createInquiry = createCaller<CreateInquiryInputType, CreateInquiryOutputType>('createInquiry');

type _CreateMaintenanceRequestCfg = typeof _CreateMaintenanceRequestEp;
export type CreateMaintenanceRequestInputType = NonNullable<_CreateMaintenanceRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateMaintenanceRequestCfg['execute']>[0]['input'];
export type CreateMaintenanceRequestOutputType = Awaited<ReturnType<_CreateMaintenanceRequestCfg['execute']>>;
export const createMaintenanceRequest = createCaller<CreateMaintenanceRequestInputType, CreateMaintenanceRequestOutputType>('createMaintenanceRequest');

type _CreateRentPaymentCfg = typeof _CreateRentPaymentEp;
export type CreateRentPaymentInputType = NonNullable<_CreateRentPaymentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateRentPaymentCfg['execute']>[0]['input'];
export type CreateRentPaymentOutputType = Awaited<ReturnType<_CreateRentPaymentCfg['execute']>>;
export const createRentPayment = createCaller<CreateRentPaymentInputType, CreateRentPaymentOutputType>('createRentPayment');

type _GetAccountProfileCfg = typeof _GetAccountProfileEp;
export type GetAccountProfileInputType = NonNullable<_GetAccountProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAccountProfileCfg['execute']>[0]['input'];
export type GetAccountProfileOutputType = Awaited<ReturnType<_GetAccountProfileCfg['execute']>>;
export const getAccountProfile = createCaller<GetAccountProfileInputType, GetAccountProfileOutputType>('getAccountProfile');

type _GetMyApplicationCfg = typeof _GetMyApplicationEp;
export type GetMyApplicationInputType = NonNullable<_GetMyApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetMyApplicationCfg['execute']>[0]['input'];
export type GetMyApplicationOutputType = Awaited<ReturnType<_GetMyApplicationCfg['execute']>>;
export const getMyApplication = createCaller<GetMyApplicationInputType, GetMyApplicationOutputType>('getMyApplication');

type _GetOwnerOverviewCfg = typeof _GetOwnerOverviewEp;
export type GetOwnerOverviewInputType = NonNullable<_GetOwnerOverviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOwnerOverviewCfg['execute']>[0]['input'];
export type GetOwnerOverviewOutputType = Awaited<ReturnType<_GetOwnerOverviewCfg['execute']>>;
export const getOwnerOverview = createCaller<GetOwnerOverviewInputType, GetOwnerOverviewOutputType>('getOwnerOverview');

type _GetOwnerPropertyCfg = typeof _GetOwnerPropertyEp;
export type GetOwnerPropertyInputType = NonNullable<_GetOwnerPropertyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOwnerPropertyCfg['execute']>[0]['input'];
export type GetOwnerPropertyOutputType = Awaited<ReturnType<_GetOwnerPropertyCfg['execute']>>;
export const getOwnerProperty = createCaller<GetOwnerPropertyInputType, GetOwnerPropertyOutputType>('getOwnerProperty');

type _GetOwnerStatementCfg = typeof _GetOwnerStatementEp;
export type GetOwnerStatementInputType = NonNullable<_GetOwnerStatementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOwnerStatementCfg['execute']>[0]['input'];
export type GetOwnerStatementOutputType = Awaited<ReturnType<_GetOwnerStatementCfg['execute']>>;
export const getOwnerStatement = createCaller<GetOwnerStatementInputType, GetOwnerStatementOutputType>('getOwnerStatement');

type _GetOwnerStatementPdfCfg = typeof _GetOwnerStatementPdfEp;
export type GetOwnerStatementPdfInputType = NonNullable<_GetOwnerStatementPdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOwnerStatementPdfCfg['execute']>[0]['input'];
export type GetOwnerStatementPdfOutputType = Awaited<ReturnType<_GetOwnerStatementPdfCfg['execute']>>;
export const getOwnerStatementPdf = createCaller<GetOwnerStatementPdfInputType, GetOwnerStatementPdfOutputType>('getOwnerStatementPdf');

type _GetPaymentReceiptCfg = typeof _GetPaymentReceiptEp;
export type GetPaymentReceiptInputType = NonNullable<_GetPaymentReceiptCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPaymentReceiptCfg['execute']>[0]['input'];
export type GetPaymentReceiptOutputType = Awaited<ReturnType<_GetPaymentReceiptCfg['execute']>>;
export const getPaymentReceipt = createCaller<GetPaymentReceiptInputType, GetPaymentReceiptOutputType>('getPaymentReceipt');

type _GetPortalCfg = typeof _GetPortalEp;
export type GetPortalInputType = NonNullable<_GetPortalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPortalCfg['execute']>[0]['input'];
export type GetPortalOutputType = Awaited<ReturnType<_GetPortalCfg['execute']>>;
export const getPortal = createCaller<GetPortalInputType, GetPortalOutputType>('getPortal');

type _GetPortalMeCfg = typeof _GetPortalMeEp;
export type GetPortalMeInputType = NonNullable<_GetPortalMeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPortalMeCfg['execute']>[0]['input'];
export type GetPortalMeOutputType = Awaited<ReturnType<_GetPortalMeCfg['execute']>>;
export const getPortalMe = createCaller<GetPortalMeInputType, GetPortalMeOutputType>('getPortalMe');

type _GetPublicListingCfg = typeof _GetPublicListingEp;
export type GetPublicListingInputType = NonNullable<_GetPublicListingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicListingCfg['execute']>[0]['input'];
export type GetPublicListingOutputType = Awaited<ReturnType<_GetPublicListingCfg['execute']>>;
export const getPublicListing = createCaller<GetPublicListingInputType, GetPublicListingOutputType>('getPublicListing');

type _GetResidentHomeCfg = typeof _GetResidentHomeEp;
export type GetResidentHomeInputType = NonNullable<_GetResidentHomeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetResidentHomeCfg['execute']>[0]['input'];
export type GetResidentHomeOutputType = Awaited<ReturnType<_GetResidentHomeCfg['execute']>>;
export const getResidentHome = createCaller<GetResidentHomeInputType, GetResidentHomeOutputType>('getResidentHome');

type _GetResidentLeaseCfg = typeof _GetResidentLeaseEp;
export type GetResidentLeaseInputType = NonNullable<_GetResidentLeaseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetResidentLeaseCfg['execute']>[0]['input'];
export type GetResidentLeaseOutputType = Awaited<ReturnType<_GetResidentLeaseCfg['execute']>>;
export const getResidentLease = createCaller<GetResidentLeaseInputType, GetResidentLeaseOutputType>('getResidentLease');

type _GetResidentRequestCfg = typeof _GetResidentRequestEp;
export type GetResidentRequestInputType = NonNullable<_GetResidentRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetResidentRequestCfg['execute']>[0]['input'];
export type GetResidentRequestOutputType = Awaited<ReturnType<_GetResidentRequestCfg['execute']>>;
export const getResidentRequest = createCaller<GetResidentRequestInputType, GetResidentRequestOutputType>('getResidentRequest');

type _GetVendorProfileCfg = typeof _GetVendorProfileEp;
export type GetVendorProfileInputType = NonNullable<_GetVendorProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetVendorProfileCfg['execute']>[0]['input'];
export type GetVendorProfileOutputType = Awaited<ReturnType<_GetVendorProfileCfg['execute']>>;
export const getVendorProfile = createCaller<GetVendorProfileInputType, GetVendorProfileOutputType>('getVendorProfile');

type _GetVendorWorkOrderCfg = typeof _GetVendorWorkOrderEp;
export type GetVendorWorkOrderInputType = NonNullable<_GetVendorWorkOrderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetVendorWorkOrderCfg['execute']>[0]['input'];
export type GetVendorWorkOrderOutputType = Awaited<ReturnType<_GetVendorWorkOrderCfg['execute']>>;
export const getVendorWorkOrder = createCaller<GetVendorWorkOrderInputType, GetVendorWorkOrderOutputType>('getVendorWorkOrder');

type _ListMyApplicationsCfg = typeof _ListMyApplicationsEp;
export type ListMyApplicationsInputType = NonNullable<_ListMyApplicationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListMyApplicationsCfg['execute']>[0]['input'];
export type ListMyApplicationsOutputType = Awaited<ReturnType<_ListMyApplicationsCfg['execute']>>;
export const listMyApplications = createCaller<ListMyApplicationsInputType, ListMyApplicationsOutputType>('listMyApplications');

type _ListOwnerApprovalsCfg = typeof _ListOwnerApprovalsEp;
export type ListOwnerApprovalsInputType = NonNullable<_ListOwnerApprovalsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListOwnerApprovalsCfg['execute']>[0]['input'];
export type ListOwnerApprovalsOutputType = Awaited<ReturnType<_ListOwnerApprovalsCfg['execute']>>;
export const listOwnerApprovals = createCaller<ListOwnerApprovalsInputType, ListOwnerApprovalsOutputType>('listOwnerApprovals');

type _ListOwnerDocumentsCfg = typeof _ListOwnerDocumentsEp;
export type ListOwnerDocumentsInputType = NonNullable<_ListOwnerDocumentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListOwnerDocumentsCfg['execute']>[0]['input'];
export type ListOwnerDocumentsOutputType = Awaited<ReturnType<_ListOwnerDocumentsCfg['execute']>>;
export const listOwnerDocuments = createCaller<ListOwnerDocumentsInputType, ListOwnerDocumentsOutputType>('listOwnerDocuments');

type _ListOwnerMessagesCfg = typeof _ListOwnerMessagesEp;
export type ListOwnerMessagesInputType = NonNullable<_ListOwnerMessagesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListOwnerMessagesCfg['execute']>[0]['input'];
export type ListOwnerMessagesOutputType = Awaited<ReturnType<_ListOwnerMessagesCfg['execute']>>;
export const listOwnerMessages = createCaller<ListOwnerMessagesInputType, ListOwnerMessagesOutputType>('listOwnerMessages');

type _ListPublicListingsCfg = typeof _ListPublicListingsEp;
export type ListPublicListingsInputType = NonNullable<_ListPublicListingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPublicListingsCfg['execute']>[0]['input'];
export type ListPublicListingsOutputType = Awaited<ReturnType<_ListPublicListingsCfg['execute']>>;
export const listPublicListings = createCaller<ListPublicListingsInputType, ListPublicListingsOutputType>('listPublicListings');

type _ListResidentDocumentsCfg = typeof _ListResidentDocumentsEp;
export type ListResidentDocumentsInputType = NonNullable<_ListResidentDocumentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListResidentDocumentsCfg['execute']>[0]['input'];
export type ListResidentDocumentsOutputType = Awaited<ReturnType<_ListResidentDocumentsCfg['execute']>>;
export const listResidentDocuments = createCaller<ListResidentDocumentsInputType, ListResidentDocumentsOutputType>('listResidentDocuments');

type _ListResidentLedgerCfg = typeof _ListResidentLedgerEp;
export type ListResidentLedgerInputType = NonNullable<_ListResidentLedgerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListResidentLedgerCfg['execute']>[0]['input'];
export type ListResidentLedgerOutputType = Awaited<ReturnType<_ListResidentLedgerCfg['execute']>>;
export const listResidentLedger = createCaller<ListResidentLedgerInputType, ListResidentLedgerOutputType>('listResidentLedger');

type _ListResidentMessagesCfg = typeof _ListResidentMessagesEp;
export type ListResidentMessagesInputType = NonNullable<_ListResidentMessagesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListResidentMessagesCfg['execute']>[0]['input'];
export type ListResidentMessagesOutputType = Awaited<ReturnType<_ListResidentMessagesCfg['execute']>>;
export const listResidentMessages = createCaller<ListResidentMessagesInputType, ListResidentMessagesOutputType>('listResidentMessages');

type _ListResidentRequestsCfg = typeof _ListResidentRequestsEp;
export type ListResidentRequestsInputType = NonNullable<_ListResidentRequestsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListResidentRequestsCfg['execute']>[0]['input'];
export type ListResidentRequestsOutputType = Awaited<ReturnType<_ListResidentRequestsCfg['execute']>>;
export const listResidentRequests = createCaller<ListResidentRequestsInputType, ListResidentRequestsOutputType>('listResidentRequests');

type _ListVendorBillsCfg = typeof _ListVendorBillsEp;
export type ListVendorBillsInputType = NonNullable<_ListVendorBillsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListVendorBillsCfg['execute']>[0]['input'];
export type ListVendorBillsOutputType = Awaited<ReturnType<_ListVendorBillsCfg['execute']>>;
export const listVendorBills = createCaller<ListVendorBillsInputType, ListVendorBillsOutputType>('listVendorBills');

type _ListVendorWorkOrdersCfg = typeof _ListVendorWorkOrdersEp;
export type ListVendorWorkOrdersInputType = NonNullable<_ListVendorWorkOrdersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListVendorWorkOrdersCfg['execute']>[0]['input'];
export type ListVendorWorkOrdersOutputType = Awaited<ReturnType<_ListVendorWorkOrdersCfg['execute']>>;
export const listVendorWorkOrders = createCaller<ListVendorWorkOrdersInputType, ListVendorWorkOrdersOutputType>('listVendorWorkOrders');

type _MarkOwnerMessagesReadCfg = typeof _MarkOwnerMessagesReadEp;
export type MarkOwnerMessagesReadInputType = NonNullable<_MarkOwnerMessagesReadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MarkOwnerMessagesReadCfg['execute']>[0]['input'];
export type MarkOwnerMessagesReadOutputType = Awaited<ReturnType<_MarkOwnerMessagesReadCfg['execute']>>;
export const markOwnerMessagesRead = createCaller<MarkOwnerMessagesReadInputType, MarkOwnerMessagesReadOutputType>('markOwnerMessagesRead');

type _MarkResidentMessagesReadCfg = typeof _MarkResidentMessagesReadEp;
export type MarkResidentMessagesReadInputType = NonNullable<_MarkResidentMessagesReadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MarkResidentMessagesReadCfg['execute']>[0]['input'];
export type MarkResidentMessagesReadOutputType = Awaited<ReturnType<_MarkResidentMessagesReadCfg['execute']>>;
export const markResidentMessagesRead = createCaller<MarkResidentMessagesReadInputType, MarkResidentMessagesReadOutputType>('markResidentMessagesRead');

type _NotifyOfficePaidCfg = typeof _NotifyOfficePaidEp;
export type NotifyOfficePaidInputType = NonNullable<_NotifyOfficePaidCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_NotifyOfficePaidCfg['execute']>[0]['input'];
export type NotifyOfficePaidOutputType = Awaited<ReturnType<_NotifyOfficePaidCfg['execute']>>;
export const notifyOfficePaid = createCaller<NotifyOfficePaidInputType, NotifyOfficePaidOutputType>('notifyOfficePaid');

type _RateRequestCfg = typeof _RateRequestEp;
export type RateRequestInputType = NonNullable<_RateRequestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RateRequestCfg['execute']>[0]['input'];
export type RateRequestOutputType = Awaited<ReturnType<_RateRequestCfg['execute']>>;
export const rateRequest = createCaller<RateRequestInputType, RateRequestOutputType>('rateRequest');

type _RespondToApprovalCfg = typeof _RespondToApprovalEp;
export type RespondToApprovalInputType = NonNullable<_RespondToApprovalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RespondToApprovalCfg['execute']>[0]['input'];
export type RespondToApprovalOutputType = Awaited<ReturnType<_RespondToApprovalCfg['execute']>>;
export const respondToApproval = createCaller<RespondToApprovalInputType, RespondToApprovalOutputType>('respondToApproval');

type _RespondToRenewalCfg = typeof _RespondToRenewalEp;
export type RespondToRenewalInputType = NonNullable<_RespondToRenewalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RespondToRenewalCfg['execute']>[0]['input'];
export type RespondToRenewalOutputType = Awaited<ReturnType<_RespondToRenewalCfg['execute']>>;
export const respondToRenewal = createCaller<RespondToRenewalInputType, RespondToRenewalOutputType>('respondToRenewal');

type _SaveApplicationDraftCfg = typeof _SaveApplicationDraftEp;
export type SaveApplicationDraftInputType = NonNullable<_SaveApplicationDraftCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveApplicationDraftCfg['execute']>[0]['input'];
export type SaveApplicationDraftOutputType = Awaited<ReturnType<_SaveApplicationDraftCfg['execute']>>;
export const saveApplicationDraft = createCaller<SaveApplicationDraftInputType, SaveApplicationDraftOutputType>('saveApplicationDraft');

type _SendApplicationMessageCfg = typeof _SendApplicationMessageEp;
export type SendApplicationMessageInputType = NonNullable<_SendApplicationMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendApplicationMessageCfg['execute']>[0]['input'];
export type SendApplicationMessageOutputType = Awaited<ReturnType<_SendApplicationMessageCfg['execute']>>;
export const sendApplicationMessage = createCaller<SendApplicationMessageInputType, SendApplicationMessageOutputType>('sendApplicationMessage');

type _SendOwnerMessageCfg = typeof _SendOwnerMessageEp;
export type SendOwnerMessageInputType = NonNullable<_SendOwnerMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendOwnerMessageCfg['execute']>[0]['input'];
export type SendOwnerMessageOutputType = Awaited<ReturnType<_SendOwnerMessageCfg['execute']>>;
export const sendOwnerMessage = createCaller<SendOwnerMessageInputType, SendOwnerMessageOutputType>('sendOwnerMessage');

type _SendResidentMessageCfg = typeof _SendResidentMessageEp;
export type SendResidentMessageInputType = NonNullable<_SendResidentMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendResidentMessageCfg['execute']>[0]['input'];
export type SendResidentMessageOutputType = Awaited<ReturnType<_SendResidentMessageCfg['execute']>>;
export const sendResidentMessage = createCaller<SendResidentMessageInputType, SendResidentMessageOutputType>('sendResidentMessage');

type _SettleOnlinePaymentsCfg = typeof _SettleOnlinePaymentsEp;
export type SettleOnlinePaymentsInputType = NonNullable<_SettleOnlinePaymentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SettleOnlinePaymentsCfg['execute']>[0]['input'];
export type SettleOnlinePaymentsOutputType = Awaited<ReturnType<_SettleOnlinePaymentsCfg['execute']>>;
export const settleOnlinePayments = createCaller<SettleOnlinePaymentsInputType, SettleOnlinePaymentsOutputType>('settleOnlinePayments');

type _SignLeaseCfg = typeof _SignLeaseEp;
export type SignLeaseInputType = NonNullable<_SignLeaseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SignLeaseCfg['execute']>[0]['input'];
export type SignLeaseOutputType = Awaited<ReturnType<_SignLeaseCfg['execute']>>;
export const signLease = createCaller<SignLeaseInputType, SignLeaseOutputType>('signLease');

type _SubmitApplicationCfg = typeof _SubmitApplicationEp;
export type SubmitApplicationInputType = NonNullable<_SubmitApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitApplicationCfg['execute']>[0]['input'];
export type SubmitApplicationOutputType = Awaited<ReturnType<_SubmitApplicationCfg['execute']>>;
export const submitApplication = createCaller<SubmitApplicationInputType, SubmitApplicationOutputType>('submitApplication');

type _SubmitNoticeCfg = typeof _SubmitNoticeEp;
export type SubmitNoticeInputType = NonNullable<_SubmitNoticeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitNoticeCfg['execute']>[0]['input'];
export type SubmitNoticeOutputType = Awaited<ReturnType<_SubmitNoticeCfg['execute']>>;
export const submitNotice = createCaller<SubmitNoticeInputType, SubmitNoticeOutputType>('submitNotice');

type _SubmitVendorInvoiceCfg = typeof _SubmitVendorInvoiceEp;
export type SubmitVendorInvoiceInputType = NonNullable<_SubmitVendorInvoiceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitVendorInvoiceCfg['execute']>[0]['input'];
export type SubmitVendorInvoiceOutputType = Awaited<ReturnType<_SubmitVendorInvoiceCfg['execute']>>;
export const submitVendorInvoice = createCaller<SubmitVendorInvoiceInputType, SubmitVendorInvoiceOutputType>('submitVendorInvoice');

type _UpdateAccountProfileCfg = typeof _UpdateAccountProfileEp;
export type UpdateAccountProfileInputType = NonNullable<_UpdateAccountProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateAccountProfileCfg['execute']>[0]['input'];
export type UpdateAccountProfileOutputType = Awaited<ReturnType<_UpdateAccountProfileCfg['execute']>>;
export const updateAccountProfile = createCaller<UpdateAccountProfileInputType, UpdateAccountProfileOutputType>('updateAccountProfile');

type _UpdateVendorProfileCfg = typeof _UpdateVendorProfileEp;
export type UpdateVendorProfileInputType = NonNullable<_UpdateVendorProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateVendorProfileCfg['execute']>[0]['input'];
export type UpdateVendorProfileOutputType = Awaited<ReturnType<_UpdateVendorProfileCfg['execute']>>;
export const updateVendorProfile = createCaller<UpdateVendorProfileInputType, UpdateVendorProfileOutputType>('updateVendorProfile');

type _UpdateVendorWorkOrderCfg = typeof _UpdateVendorWorkOrderEp;
export type UpdateVendorWorkOrderInputType = NonNullable<_UpdateVendorWorkOrderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateVendorWorkOrderCfg['execute']>[0]['input'];
export type UpdateVendorWorkOrderOutputType = Awaited<ReturnType<_UpdateVendorWorkOrderCfg['execute']>>;
export const updateVendorWorkOrder = createCaller<UpdateVendorWorkOrderInputType, UpdateVendorWorkOrderOutputType>('updateVendorWorkOrder');

type _UploadResidentDocumentCfg = typeof _UploadResidentDocumentEp;
export type UploadResidentDocumentInputType = NonNullable<_UploadResidentDocumentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UploadResidentDocumentCfg['execute']>[0]['input'];
export type UploadResidentDocumentOutputType = Awaited<ReturnType<_UploadResidentDocumentCfg['execute']>>;
export const uploadResidentDocument = createCaller<UploadResidentDocumentInputType, UploadResidentDocumentOutputType>('uploadResidentDocument');

type _UploadVendorDocumentCfg = typeof _UploadVendorDocumentEp;
export type UploadVendorDocumentInputType = NonNullable<_UploadVendorDocumentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UploadVendorDocumentCfg['execute']>[0]['input'];
export type UploadVendorDocumentOutputType = Awaited<ReturnType<_UploadVendorDocumentCfg['execute']>>;
export const uploadVendorDocument = createCaller<UploadVendorDocumentInputType, UploadVendorDocumentOutputType>('uploadVendorDocument');

type _WithdrawApplicationCfg = typeof _WithdrawApplicationEp;
export type WithdrawApplicationInputType = NonNullable<_WithdrawApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_WithdrawApplicationCfg['execute']>[0]['input'];
export type WithdrawApplicationOutputType = Awaited<ReturnType<_WithdrawApplicationCfg['execute']>>;
export const withdrawApplication = createCaller<WithdrawApplicationInputType, WithdrawApplicationOutputType>('withdrawApplication');


export const api = {
  acknowledgeInspection,
  addRequestMessage,
  addVendorWorkOrderMessage,
  cancelRequest,
  confirmApplicationFeePayment,
  confirmRentPayment,
  createApplicationFeePayment,
  createInquiry,
  createMaintenanceRequest,
  createRentPayment,
  getAccountProfile,
  getMyApplication,
  getOwnerOverview,
  getOwnerProperty,
  getOwnerStatement,
  getOwnerStatementPdf,
  getPaymentReceipt,
  getPortal,
  getPortalMe,
  getPublicListing,
  getResidentHome,
  getResidentLease,
  getResidentRequest,
  getVendorProfile,
  getVendorWorkOrder,
  listMyApplications,
  listOwnerApprovals,
  listOwnerDocuments,
  listOwnerMessages,
  listPublicListings,
  listResidentDocuments,
  listResidentLedger,
  listResidentMessages,
  listResidentRequests,
  listVendorBills,
  listVendorWorkOrders,
  markOwnerMessagesRead,
  markResidentMessagesRead,
  notifyOfficePaid,
  rateRequest,
  respondToApproval,
  respondToRenewal,
  saveApplicationDraft,
  sendApplicationMessage,
  sendOwnerMessage,
  sendResidentMessage,
  settleOnlinePayments,
  signLease,
  submitApplication,
  submitNotice,
  submitVendorInvoice,
  updateAccountProfile,
  updateVendorProfile,
  updateVendorWorkOrder,
  uploadResidentDocument,
  uploadVendorDocument,
  withdrawApplication,
};
