// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AddApplicationMessageEp } from '../src/api/addApplicationMessage';
import type { default as _AddWorkOrderCommentEp } from '../src/api/addWorkOrderComment';
import type { default as _AiListingDescriptionEp } from '../src/api/aiListingDescription';
import type { default as _AiTriageWorkOrderEp } from '../src/api/aiTriageWorkOrder';
import type { default as _BootstrapEp } from '../src/api/bootstrap';
import type { default as _ClearDemoDataEp } from '../src/api/clearDemoData';
import type { default as _CreateBillEp } from '../src/api/createBill';
import type { default as _CreateLeaseStaffEp } from '../src/api/createLeaseStaff';
import type { default as _CreateWorkOrderEp } from '../src/api/createWorkOrder';
import type { default as _DecideApplicationEp } from '../src/api/decideApplication';
import type { default as _GenerateScheduleNowEp } from '../src/api/generateScheduleNow';
import type { default as _GetAccountRegisterEp } from '../src/api/getAccountRegister';
import type { default as _GetAnnouncementEp } from '../src/api/getAnnouncement';
import type { default as _GetApplicationEp } from '../src/api/getApplication';
import type { default as _GetBankingEp } from '../src/api/getBanking';
import type { default as _GetChartBalancesEp } from '../src/api/getChartBalances';
import type { default as _GetDashboardEp } from '../src/api/getDashboard';
import type { default as _GetInquiryEp } from '../src/api/getInquiry';
import type { default as _GetInspectionEp } from '../src/api/getInspection';
import type { default as _GetLeaseEp } from '../src/api/getLease';
import type { default as _GetLeaseLedgerEp } from '../src/api/getLeaseLedger';
import type { default as _GetListingEp } from '../src/api/getListing';
import type { default as _GetOrgSettingsEp } from '../src/api/getOrgSettings';
import type { default as _GetOwnerEp } from '../src/api/getOwner';
import type { default as _GetOwnerFundsEp } from '../src/api/getOwnerFunds';
import type { default as _GetOwnerStatementStaffEp } from '../src/api/getOwnerStatementStaff';
import type { default as _GetPropertyEp } from '../src/api/getProperty';
import type { default as _GetPropertyFinancialsEp } from '../src/api/getPropertyFinancials';
import type { default as _GetReceivablesEp } from '../src/api/getReceivables';
import type { default as _GetReconciliationEp } from '../src/api/getReconciliation';
import type { default as _GetResidentEp } from '../src/api/getResident';
import type { default as _GetTaskEp } from '../src/api/getTask';
import type { default as _GetThreadEp } from '../src/api/getThread';
import type { default as _GetTransactionEp } from '../src/api/getTransaction';
import type { default as _GetUnitEp } from '../src/api/getUnit';
import type { default as _GetVendorEp } from '../src/api/getVendor';
import type { default as _GetWorkOrderEp } from '../src/api/getWorkOrder';
import type { default as _InspectionReportPdfEp } from '../src/api/inspectionReportPdf';
import type { default as _InviteTeamMemberEp } from '../src/api/inviteTeamMember';
import type { default as _LeaseLifecycleEp } from '../src/api/leaseLifecycle';
import type { default as _ListAnnouncementsEp } from '../src/api/listAnnouncements';
import type { default as _ListApplicationsEp } from '../src/api/listApplications';
import type { default as _ListBillPaymentsEp } from '../src/api/listBillPayments';
import type { default as _ListBillsEp } from '../src/api/listBills';
import type { default as _ListDocumentsEp } from '../src/api/listDocuments';
import type { default as _ListEmailTemplatesEp } from '../src/api/listEmailTemplates';
import type { default as _ListInquiriesEp } from '../src/api/listInquiries';
import type { default as _ListInspectionsEp } from '../src/api/listInspections';
import type { default as _ListLeasesEp } from '../src/api/listLeases';
import type { default as _ListListingsEp } from '../src/api/listListings';
import type { default as _ListNotificationsEp } from '../src/api/listNotifications';
import type { default as _ListOwnerTransactionsEp } from '../src/api/listOwnerTransactions';
import type { default as _ListOwnersEp } from '../src/api/listOwners';
import type { default as _ListPaymentsEp } from '../src/api/listPayments';
import type { default as _ListPropertiesEp } from '../src/api/listProperties';
import type { default as _ListPropertyLeasesEp } from '../src/api/listPropertyLeases';
import type { default as _ListResidentsEp } from '../src/api/listResidents';
import type { default as _ListSchedulesEp } from '../src/api/listSchedules';
import type { default as _ListTasksEp } from '../src/api/listTasks';
import type { default as _ListTeamMembersEp } from '../src/api/listTeamMembers';
import type { default as _ListThreadsEp } from '../src/api/listThreads';
import type { default as _ListTransactionsEp } from '../src/api/listTransactions';
import type { default as _ListVacanciesEp } from '../src/api/listVacancies';
import type { default as _ListVendorsEp } from '../src/api/listVendors';
import type { default as _ListWorkOrdersEp } from '../src/api/listWorkOrders';
import type { default as _MarkThreadReadEp } from '../src/api/markThreadRead';
import type { default as _MessageResidentEp } from '../src/api/messageResident';
import type { default as _MessageVendorEp } from '../src/api/messageVendor';
import type { default as _PayVendorBillsEp } from '../src/api/payVendorBills';
import type { default as _PostBankActivityEp } from '../src/api/postBankActivity';
import type { default as _PostBulkChargesEp } from '../src/api/postBulkCharges';
import type { default as _PostJournalEp } from '../src/api/postJournal';
import type { default as _PostLeaseMoneyEp } from '../src/api/postLeaseMoney';
import type { default as _PostOwnerFundsEp } from '../src/api/postOwnerFunds';
import type { default as _PreviewAnnouncementEp } from '../src/api/previewAnnouncement';
import type { default as _PreviewMessageEp } from '../src/api/previewMessage';
import type { default as _ReplyToInquiryEp } from '../src/api/replyToInquiry';
import type { default as _ReportAgingEp } from '../src/api/reportAging';
import type { default as _ReportBalanceSheetEp } from '../src/api/reportBalanceSheet';
import type { default as _ReportCashFlowEp } from '../src/api/reportCashFlow';
import type { default as _ReportDepositsEp } from '../src/api/reportDeposits';
import type { default as _ReportExpirationsEp } from '../src/api/reportExpirations';
import type { default as _ReportGeneralLedgerEp } from '../src/api/reportGeneralLedger';
import type { default as _ReportIncomeStatementEp } from '../src/api/reportIncomeStatement';
import type { default as _ReportLeasingFunnelEp } from '../src/api/reportLeasingFunnel';
import type { default as _ReportOccupancyEp } from '../src/api/reportOccupancy';
import type { default as _ReportOwnerStatementEp } from '../src/api/reportOwnerStatement';
import type { default as _ReportPaymentsEp } from '../src/api/reportPayments';
import type { default as _ReportPdfEp } from '../src/api/reportPdf';
import type { default as _ReportRentRollEp } from '../src/api/reportRentRoll';
import type { default as _ReportTrialBalanceEp } from '../src/api/reportTrialBalance';
import type { default as _ReportVacancyEp } from '../src/api/reportVacancy';
import type { default as _ReportVendorSpendEp } from '../src/api/reportVendorSpend';
import type { default as _ReportWorkOrdersEp } from '../src/api/reportWorkOrders';
import type { default as _RunAutomationEp } from '../src/api/runAutomation';
import type { default as _RunManagementFeesEp } from '../src/api/runManagementFees';
import type { default as _SaveAccountEp } from '../src/api/saveAccount';
import type { default as _SaveAnnouncementEp } from '../src/api/saveAnnouncement';
import type { default as _SaveDocumentEp } from '../src/api/saveDocument';
import type { default as _SaveEmailTemplateEp } from '../src/api/saveEmailTemplate';
import type { default as _SaveInquiryEp } from '../src/api/saveInquiry';
import type { default as _SaveInspectionEp } from '../src/api/saveInspection';
import type { default as _SaveListingEp } from '../src/api/saveListing';
import type { default as _SaveOwnerEp } from '../src/api/saveOwner';
import type { default as _SavePropertyEp } from '../src/api/saveProperty';
import type { default as _SaveReconciliationEp } from '../src/api/saveReconciliation';
import type { default as _SaveRecurringChargeEp } from '../src/api/saveRecurringCharge';
import type { default as _SaveScheduleEp } from '../src/api/saveSchedule';
import type { default as _SaveTaskEp } from '../src/api/saveTask';
import type { default as _SaveTenantEp } from '../src/api/saveTenant';
import type { default as _SaveUnitEp } from '../src/api/saveUnit';
import type { default as _SaveVendorEp } from '../src/api/saveVendor';
import type { default as _SaveViewEp } from '../src/api/saveView';
import type { default as _ScheduleShowingEp } from '../src/api/scheduleShowing';
import type { default as _SearchEp } from '../src/api/search';
import type { default as _SeedWorkspaceEp } from '../src/api/seedWorkspace';
import type { default as _SendAnnouncementEp } from '../src/api/sendAnnouncement';
import type { default as _SendLateNoticesEp } from '../src/api/sendLateNotices';
import type { default as _SendMessagesEp } from '../src/api/sendMessages';
import type { default as _SendOwnerMessageEp } from '../src/api/sendOwnerMessage';
import type { default as _SendScheduledAnnouncementsEp } from '../src/api/sendScheduledAnnouncements';
import type { default as _SendTemplateTestEp } from '../src/api/sendTemplateTest';
import type { default as _SettleDepositEp } from '../src/api/settleDeposit';
import type { default as _UpdateApplicationEp } from '../src/api/updateApplication';
import type { default as _UpdateLeaseEp } from '../src/api/updateLease';
import type { default as _UpdateMyProfileEp } from '../src/api/updateMyProfile';
import type { default as _UpdateNotificationsEp } from '../src/api/updateNotifications';
import type { default as _UpdateOrgSettingsEp } from '../src/api/updateOrgSettings';
import type { default as _UpdateTasksEp } from '../src/api/updateTasks';
import type { default as _UpdateTeamMemberEp } from '../src/api/updateTeamMember';
import type { default as _UpdateUnitsEp } from '../src/api/updateUnits';
import type { default as _UpdateWorkOrdersEp } from '../src/api/updateWorkOrders';
import type { default as _VoidLedgerTransactionEp } from '../src/api/voidLedgerTransaction';
import type { default as _WorkOrderMoneyEp } from '../src/api/workOrderMoney';

type _AddApplicationMessageCfg = typeof _AddApplicationMessageEp;
export type AddApplicationMessageInputType = NonNullable<_AddApplicationMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AddApplicationMessageCfg['execute']>[0]['input'];
export type AddApplicationMessageOutputType = Awaited<ReturnType<_AddApplicationMessageCfg['execute']>>;
export const addApplicationMessage = createCaller<AddApplicationMessageInputType, AddApplicationMessageOutputType>('addApplicationMessage');

type _AddWorkOrderCommentCfg = typeof _AddWorkOrderCommentEp;
export type AddWorkOrderCommentInputType = NonNullable<_AddWorkOrderCommentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AddWorkOrderCommentCfg['execute']>[0]['input'];
export type AddWorkOrderCommentOutputType = Awaited<ReturnType<_AddWorkOrderCommentCfg['execute']>>;
export const addWorkOrderComment = createCaller<AddWorkOrderCommentInputType, AddWorkOrderCommentOutputType>('addWorkOrderComment');

type _AiListingDescriptionCfg = typeof _AiListingDescriptionEp;
export type AiListingDescriptionInputType = NonNullable<_AiListingDescriptionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiListingDescriptionCfg['execute']>[0]['input'];
export type AiListingDescriptionOutputType = Awaited<ReturnType<_AiListingDescriptionCfg['execute']>>;
export const aiListingDescription = createCaller<AiListingDescriptionInputType, AiListingDescriptionOutputType>('aiListingDescription');

type _AiTriageWorkOrderCfg = typeof _AiTriageWorkOrderEp;
export type AiTriageWorkOrderInputType = NonNullable<_AiTriageWorkOrderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiTriageWorkOrderCfg['execute']>[0]['input'];
export type AiTriageWorkOrderOutputType = Awaited<ReturnType<_AiTriageWorkOrderCfg['execute']>>;
export const aiTriageWorkOrder = createCaller<AiTriageWorkOrderInputType, AiTriageWorkOrderOutputType>('aiTriageWorkOrder');

type _BootstrapCfg = typeof _BootstrapEp;
export type BootstrapInputType = NonNullable<_BootstrapCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BootstrapCfg['execute']>[0]['input'];
export type BootstrapOutputType = Awaited<ReturnType<_BootstrapCfg['execute']>>;
export const bootstrap = createCaller<BootstrapInputType, BootstrapOutputType>('bootstrap');

type _ClearDemoDataCfg = typeof _ClearDemoDataEp;
export type ClearDemoDataInputType = NonNullable<_ClearDemoDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ClearDemoDataCfg['execute']>[0]['input'];
export type ClearDemoDataOutputType = Awaited<ReturnType<_ClearDemoDataCfg['execute']>>;
export const clearDemoData = createCaller<ClearDemoDataInputType, ClearDemoDataOutputType>('clearDemoData');

type _CreateBillCfg = typeof _CreateBillEp;
export type CreateBillInputType = NonNullable<_CreateBillCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateBillCfg['execute']>[0]['input'];
export type CreateBillOutputType = Awaited<ReturnType<_CreateBillCfg['execute']>>;
export const createBill = createCaller<CreateBillInputType, CreateBillOutputType>('createBill');

type _CreateLeaseStaffCfg = typeof _CreateLeaseStaffEp;
export type CreateLeaseStaffInputType = NonNullable<_CreateLeaseStaffCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateLeaseStaffCfg['execute']>[0]['input'];
export type CreateLeaseStaffOutputType = Awaited<ReturnType<_CreateLeaseStaffCfg['execute']>>;
export const createLeaseStaff = createCaller<CreateLeaseStaffInputType, CreateLeaseStaffOutputType>('createLeaseStaff');

type _CreateWorkOrderCfg = typeof _CreateWorkOrderEp;
export type CreateWorkOrderInputType = NonNullable<_CreateWorkOrderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateWorkOrderCfg['execute']>[0]['input'];
export type CreateWorkOrderOutputType = Awaited<ReturnType<_CreateWorkOrderCfg['execute']>>;
export const createWorkOrder = createCaller<CreateWorkOrderInputType, CreateWorkOrderOutputType>('createWorkOrder');

type _DecideApplicationCfg = typeof _DecideApplicationEp;
export type DecideApplicationInputType = NonNullable<_DecideApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DecideApplicationCfg['execute']>[0]['input'];
export type DecideApplicationOutputType = Awaited<ReturnType<_DecideApplicationCfg['execute']>>;
export const decideApplication = createCaller<DecideApplicationInputType, DecideApplicationOutputType>('decideApplication');

type _GenerateScheduleNowCfg = typeof _GenerateScheduleNowEp;
export type GenerateScheduleNowInputType = NonNullable<_GenerateScheduleNowCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GenerateScheduleNowCfg['execute']>[0]['input'];
export type GenerateScheduleNowOutputType = Awaited<ReturnType<_GenerateScheduleNowCfg['execute']>>;
export const generateScheduleNow = createCaller<GenerateScheduleNowInputType, GenerateScheduleNowOutputType>('generateScheduleNow');

type _GetAccountRegisterCfg = typeof _GetAccountRegisterEp;
export type GetAccountRegisterInputType = NonNullable<_GetAccountRegisterCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAccountRegisterCfg['execute']>[0]['input'];
export type GetAccountRegisterOutputType = Awaited<ReturnType<_GetAccountRegisterCfg['execute']>>;
export const getAccountRegister = createCaller<GetAccountRegisterInputType, GetAccountRegisterOutputType>('getAccountRegister');

type _GetAnnouncementCfg = typeof _GetAnnouncementEp;
export type GetAnnouncementInputType = NonNullable<_GetAnnouncementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAnnouncementCfg['execute']>[0]['input'];
export type GetAnnouncementOutputType = Awaited<ReturnType<_GetAnnouncementCfg['execute']>>;
export const getAnnouncement = createCaller<GetAnnouncementInputType, GetAnnouncementOutputType>('getAnnouncement');

type _GetApplicationCfg = typeof _GetApplicationEp;
export type GetApplicationInputType = NonNullable<_GetApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetApplicationCfg['execute']>[0]['input'];
export type GetApplicationOutputType = Awaited<ReturnType<_GetApplicationCfg['execute']>>;
export const getApplication = createCaller<GetApplicationInputType, GetApplicationOutputType>('getApplication');

type _GetBankingCfg = typeof _GetBankingEp;
export type GetBankingInputType = NonNullable<_GetBankingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetBankingCfg['execute']>[0]['input'];
export type GetBankingOutputType = Awaited<ReturnType<_GetBankingCfg['execute']>>;
export const getBanking = createCaller<GetBankingInputType, GetBankingOutputType>('getBanking');

type _GetChartBalancesCfg = typeof _GetChartBalancesEp;
export type GetChartBalancesInputType = NonNullable<_GetChartBalancesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetChartBalancesCfg['execute']>[0]['input'];
export type GetChartBalancesOutputType = Awaited<ReturnType<_GetChartBalancesCfg['execute']>>;
export const getChartBalances = createCaller<GetChartBalancesInputType, GetChartBalancesOutputType>('getChartBalances');

type _GetDashboardCfg = typeof _GetDashboardEp;
export type GetDashboardInputType = NonNullable<_GetDashboardCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetDashboardCfg['execute']>[0]['input'];
export type GetDashboardOutputType = Awaited<ReturnType<_GetDashboardCfg['execute']>>;
export const getDashboard = createCaller<GetDashboardInputType, GetDashboardOutputType>('getDashboard');

type _GetInquiryCfg = typeof _GetInquiryEp;
export type GetInquiryInputType = NonNullable<_GetInquiryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetInquiryCfg['execute']>[0]['input'];
export type GetInquiryOutputType = Awaited<ReturnType<_GetInquiryCfg['execute']>>;
export const getInquiry = createCaller<GetInquiryInputType, GetInquiryOutputType>('getInquiry');

type _GetInspectionCfg = typeof _GetInspectionEp;
export type GetInspectionInputType = NonNullable<_GetInspectionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetInspectionCfg['execute']>[0]['input'];
export type GetInspectionOutputType = Awaited<ReturnType<_GetInspectionCfg['execute']>>;
export const getInspection = createCaller<GetInspectionInputType, GetInspectionOutputType>('getInspection');

type _GetLeaseCfg = typeof _GetLeaseEp;
export type GetLeaseInputType = NonNullable<_GetLeaseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLeaseCfg['execute']>[0]['input'];
export type GetLeaseOutputType = Awaited<ReturnType<_GetLeaseCfg['execute']>>;
export const getLease = createCaller<GetLeaseInputType, GetLeaseOutputType>('getLease');

type _GetLeaseLedgerCfg = typeof _GetLeaseLedgerEp;
export type GetLeaseLedgerInputType = NonNullable<_GetLeaseLedgerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetLeaseLedgerCfg['execute']>[0]['input'];
export type GetLeaseLedgerOutputType = Awaited<ReturnType<_GetLeaseLedgerCfg['execute']>>;
export const getLeaseLedger = createCaller<GetLeaseLedgerInputType, GetLeaseLedgerOutputType>('getLeaseLedger');

type _GetListingCfg = typeof _GetListingEp;
export type GetListingInputType = NonNullable<_GetListingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetListingCfg['execute']>[0]['input'];
export type GetListingOutputType = Awaited<ReturnType<_GetListingCfg['execute']>>;
export const getListing = createCaller<GetListingInputType, GetListingOutputType>('getListing');

type _GetOrgSettingsCfg = typeof _GetOrgSettingsEp;
export type GetOrgSettingsInputType = NonNullable<_GetOrgSettingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOrgSettingsCfg['execute']>[0]['input'];
export type GetOrgSettingsOutputType = Awaited<ReturnType<_GetOrgSettingsCfg['execute']>>;
export const getOrgSettings = createCaller<GetOrgSettingsInputType, GetOrgSettingsOutputType>('getOrgSettings');

type _GetOwnerCfg = typeof _GetOwnerEp;
export type GetOwnerInputType = NonNullable<_GetOwnerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOwnerCfg['execute']>[0]['input'];
export type GetOwnerOutputType = Awaited<ReturnType<_GetOwnerCfg['execute']>>;
export const getOwner = createCaller<GetOwnerInputType, GetOwnerOutputType>('getOwner');

type _GetOwnerFundsCfg = typeof _GetOwnerFundsEp;
export type GetOwnerFundsInputType = NonNullable<_GetOwnerFundsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOwnerFundsCfg['execute']>[0]['input'];
export type GetOwnerFundsOutputType = Awaited<ReturnType<_GetOwnerFundsCfg['execute']>>;
export const getOwnerFunds = createCaller<GetOwnerFundsInputType, GetOwnerFundsOutputType>('getOwnerFunds');

type _GetOwnerStatementStaffCfg = typeof _GetOwnerStatementStaffEp;
export type GetOwnerStatementStaffInputType = NonNullable<_GetOwnerStatementStaffCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetOwnerStatementStaffCfg['execute']>[0]['input'];
export type GetOwnerStatementStaffOutputType = Awaited<ReturnType<_GetOwnerStatementStaffCfg['execute']>>;
export const getOwnerStatementStaff = createCaller<GetOwnerStatementStaffInputType, GetOwnerStatementStaffOutputType>('getOwnerStatementStaff');

type _GetPropertyCfg = typeof _GetPropertyEp;
export type GetPropertyInputType = NonNullable<_GetPropertyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPropertyCfg['execute']>[0]['input'];
export type GetPropertyOutputType = Awaited<ReturnType<_GetPropertyCfg['execute']>>;
export const getProperty = createCaller<GetPropertyInputType, GetPropertyOutputType>('getProperty');

type _GetPropertyFinancialsCfg = typeof _GetPropertyFinancialsEp;
export type GetPropertyFinancialsInputType = NonNullable<_GetPropertyFinancialsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPropertyFinancialsCfg['execute']>[0]['input'];
export type GetPropertyFinancialsOutputType = Awaited<ReturnType<_GetPropertyFinancialsCfg['execute']>>;
export const getPropertyFinancials = createCaller<GetPropertyFinancialsInputType, GetPropertyFinancialsOutputType>('getPropertyFinancials');

type _GetReceivablesCfg = typeof _GetReceivablesEp;
export type GetReceivablesInputType = NonNullable<_GetReceivablesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReceivablesCfg['execute']>[0]['input'];
export type GetReceivablesOutputType = Awaited<ReturnType<_GetReceivablesCfg['execute']>>;
export const getReceivables = createCaller<GetReceivablesInputType, GetReceivablesOutputType>('getReceivables');

type _GetReconciliationCfg = typeof _GetReconciliationEp;
export type GetReconciliationInputType = NonNullable<_GetReconciliationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetReconciliationCfg['execute']>[0]['input'];
export type GetReconciliationOutputType = Awaited<ReturnType<_GetReconciliationCfg['execute']>>;
export const getReconciliation = createCaller<GetReconciliationInputType, GetReconciliationOutputType>('getReconciliation');

type _GetResidentCfg = typeof _GetResidentEp;
export type GetResidentInputType = NonNullable<_GetResidentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetResidentCfg['execute']>[0]['input'];
export type GetResidentOutputType = Awaited<ReturnType<_GetResidentCfg['execute']>>;
export const getResident = createCaller<GetResidentInputType, GetResidentOutputType>('getResident');

type _GetTaskCfg = typeof _GetTaskEp;
export type GetTaskInputType = NonNullable<_GetTaskCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetTaskCfg['execute']>[0]['input'];
export type GetTaskOutputType = Awaited<ReturnType<_GetTaskCfg['execute']>>;
export const getTask = createCaller<GetTaskInputType, GetTaskOutputType>('getTask');

type _GetThreadCfg = typeof _GetThreadEp;
export type GetThreadInputType = NonNullable<_GetThreadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetThreadCfg['execute']>[0]['input'];
export type GetThreadOutputType = Awaited<ReturnType<_GetThreadCfg['execute']>>;
export const getThread = createCaller<GetThreadInputType, GetThreadOutputType>('getThread');

type _GetTransactionCfg = typeof _GetTransactionEp;
export type GetTransactionInputType = NonNullable<_GetTransactionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetTransactionCfg['execute']>[0]['input'];
export type GetTransactionOutputType = Awaited<ReturnType<_GetTransactionCfg['execute']>>;
export const getTransaction = createCaller<GetTransactionInputType, GetTransactionOutputType>('getTransaction');

type _GetUnitCfg = typeof _GetUnitEp;
export type GetUnitInputType = NonNullable<_GetUnitCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetUnitCfg['execute']>[0]['input'];
export type GetUnitOutputType = Awaited<ReturnType<_GetUnitCfg['execute']>>;
export const getUnit = createCaller<GetUnitInputType, GetUnitOutputType>('getUnit');

type _GetVendorCfg = typeof _GetVendorEp;
export type GetVendorInputType = NonNullable<_GetVendorCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetVendorCfg['execute']>[0]['input'];
export type GetVendorOutputType = Awaited<ReturnType<_GetVendorCfg['execute']>>;
export const getVendor = createCaller<GetVendorInputType, GetVendorOutputType>('getVendor');

type _GetWorkOrderCfg = typeof _GetWorkOrderEp;
export type GetWorkOrderInputType = NonNullable<_GetWorkOrderCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetWorkOrderCfg['execute']>[0]['input'];
export type GetWorkOrderOutputType = Awaited<ReturnType<_GetWorkOrderCfg['execute']>>;
export const getWorkOrder = createCaller<GetWorkOrderInputType, GetWorkOrderOutputType>('getWorkOrder');

type _InspectionReportPdfCfg = typeof _InspectionReportPdfEp;
export type InspectionReportPdfInputType = NonNullable<_InspectionReportPdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_InspectionReportPdfCfg['execute']>[0]['input'];
export type InspectionReportPdfOutputType = Awaited<ReturnType<_InspectionReportPdfCfg['execute']>>;
export const inspectionReportPdf = createCaller<InspectionReportPdfInputType, InspectionReportPdfOutputType>('inspectionReportPdf');

type _InviteTeamMemberCfg = typeof _InviteTeamMemberEp;
export type InviteTeamMemberInputType = NonNullable<_InviteTeamMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_InviteTeamMemberCfg['execute']>[0]['input'];
export type InviteTeamMemberOutputType = Awaited<ReturnType<_InviteTeamMemberCfg['execute']>>;
export const inviteTeamMember = createCaller<InviteTeamMemberInputType, InviteTeamMemberOutputType>('inviteTeamMember');

type _LeaseLifecycleCfg = typeof _LeaseLifecycleEp;
export type LeaseLifecycleInputType = NonNullable<_LeaseLifecycleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_LeaseLifecycleCfg['execute']>[0]['input'];
export type LeaseLifecycleOutputType = Awaited<ReturnType<_LeaseLifecycleCfg['execute']>>;
export const leaseLifecycle = createCaller<LeaseLifecycleInputType, LeaseLifecycleOutputType>('leaseLifecycle');

type _ListAnnouncementsCfg = typeof _ListAnnouncementsEp;
export type ListAnnouncementsInputType = NonNullable<_ListAnnouncementsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListAnnouncementsCfg['execute']>[0]['input'];
export type ListAnnouncementsOutputType = Awaited<ReturnType<_ListAnnouncementsCfg['execute']>>;
export const listAnnouncements = createCaller<ListAnnouncementsInputType, ListAnnouncementsOutputType>('listAnnouncements');

type _ListApplicationsCfg = typeof _ListApplicationsEp;
export type ListApplicationsInputType = NonNullable<_ListApplicationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListApplicationsCfg['execute']>[0]['input'];
export type ListApplicationsOutputType = Awaited<ReturnType<_ListApplicationsCfg['execute']>>;
export const listApplications = createCaller<ListApplicationsInputType, ListApplicationsOutputType>('listApplications');

type _ListBillPaymentsCfg = typeof _ListBillPaymentsEp;
export type ListBillPaymentsInputType = NonNullable<_ListBillPaymentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListBillPaymentsCfg['execute']>[0]['input'];
export type ListBillPaymentsOutputType = Awaited<ReturnType<_ListBillPaymentsCfg['execute']>>;
export const listBillPayments = createCaller<ListBillPaymentsInputType, ListBillPaymentsOutputType>('listBillPayments');

type _ListBillsCfg = typeof _ListBillsEp;
export type ListBillsInputType = NonNullable<_ListBillsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListBillsCfg['execute']>[0]['input'];
export type ListBillsOutputType = Awaited<ReturnType<_ListBillsCfg['execute']>>;
export const listBills = createCaller<ListBillsInputType, ListBillsOutputType>('listBills');

type _ListDocumentsCfg = typeof _ListDocumentsEp;
export type ListDocumentsInputType = NonNullable<_ListDocumentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListDocumentsCfg['execute']>[0]['input'];
export type ListDocumentsOutputType = Awaited<ReturnType<_ListDocumentsCfg['execute']>>;
export const listDocuments = createCaller<ListDocumentsInputType, ListDocumentsOutputType>('listDocuments');

type _ListEmailTemplatesCfg = typeof _ListEmailTemplatesEp;
export type ListEmailTemplatesInputType = NonNullable<_ListEmailTemplatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListEmailTemplatesCfg['execute']>[0]['input'];
export type ListEmailTemplatesOutputType = Awaited<ReturnType<_ListEmailTemplatesCfg['execute']>>;
export const listEmailTemplates = createCaller<ListEmailTemplatesInputType, ListEmailTemplatesOutputType>('listEmailTemplates');

type _ListInquiriesCfg = typeof _ListInquiriesEp;
export type ListInquiriesInputType = NonNullable<_ListInquiriesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInquiriesCfg['execute']>[0]['input'];
export type ListInquiriesOutputType = Awaited<ReturnType<_ListInquiriesCfg['execute']>>;
export const listInquiries = createCaller<ListInquiriesInputType, ListInquiriesOutputType>('listInquiries');

type _ListInspectionsCfg = typeof _ListInspectionsEp;
export type ListInspectionsInputType = NonNullable<_ListInspectionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInspectionsCfg['execute']>[0]['input'];
export type ListInspectionsOutputType = Awaited<ReturnType<_ListInspectionsCfg['execute']>>;
export const listInspections = createCaller<ListInspectionsInputType, ListInspectionsOutputType>('listInspections');

type _ListLeasesCfg = typeof _ListLeasesEp;
export type ListLeasesInputType = NonNullable<_ListLeasesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListLeasesCfg['execute']>[0]['input'];
export type ListLeasesOutputType = Awaited<ReturnType<_ListLeasesCfg['execute']>>;
export const listLeases = createCaller<ListLeasesInputType, ListLeasesOutputType>('listLeases');

type _ListListingsCfg = typeof _ListListingsEp;
export type ListListingsInputType = NonNullable<_ListListingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListListingsCfg['execute']>[0]['input'];
export type ListListingsOutputType = Awaited<ReturnType<_ListListingsCfg['execute']>>;
export const listListings = createCaller<ListListingsInputType, ListListingsOutputType>('listListings');

type _ListNotificationsCfg = typeof _ListNotificationsEp;
export type ListNotificationsInputType = NonNullable<_ListNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListNotificationsCfg['execute']>[0]['input'];
export type ListNotificationsOutputType = Awaited<ReturnType<_ListNotificationsCfg['execute']>>;
export const listNotifications = createCaller<ListNotificationsInputType, ListNotificationsOutputType>('listNotifications');

type _ListOwnerTransactionsCfg = typeof _ListOwnerTransactionsEp;
export type ListOwnerTransactionsInputType = NonNullable<_ListOwnerTransactionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListOwnerTransactionsCfg['execute']>[0]['input'];
export type ListOwnerTransactionsOutputType = Awaited<ReturnType<_ListOwnerTransactionsCfg['execute']>>;
export const listOwnerTransactions = createCaller<ListOwnerTransactionsInputType, ListOwnerTransactionsOutputType>('listOwnerTransactions');

type _ListOwnersCfg = typeof _ListOwnersEp;
export type ListOwnersInputType = NonNullable<_ListOwnersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListOwnersCfg['execute']>[0]['input'];
export type ListOwnersOutputType = Awaited<ReturnType<_ListOwnersCfg['execute']>>;
export const listOwners = createCaller<ListOwnersInputType, ListOwnersOutputType>('listOwners');

type _ListPaymentsCfg = typeof _ListPaymentsEp;
export type ListPaymentsInputType = NonNullable<_ListPaymentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPaymentsCfg['execute']>[0]['input'];
export type ListPaymentsOutputType = Awaited<ReturnType<_ListPaymentsCfg['execute']>>;
export const listPayments = createCaller<ListPaymentsInputType, ListPaymentsOutputType>('listPayments');

type _ListPropertiesCfg = typeof _ListPropertiesEp;
export type ListPropertiesInputType = NonNullable<_ListPropertiesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPropertiesCfg['execute']>[0]['input'];
export type ListPropertiesOutputType = Awaited<ReturnType<_ListPropertiesCfg['execute']>>;
export const listProperties = createCaller<ListPropertiesInputType, ListPropertiesOutputType>('listProperties');

type _ListPropertyLeasesCfg = typeof _ListPropertyLeasesEp;
export type ListPropertyLeasesInputType = NonNullable<_ListPropertyLeasesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPropertyLeasesCfg['execute']>[0]['input'];
export type ListPropertyLeasesOutputType = Awaited<ReturnType<_ListPropertyLeasesCfg['execute']>>;
export const listPropertyLeases = createCaller<ListPropertyLeasesInputType, ListPropertyLeasesOutputType>('listPropertyLeases');

type _ListResidentsCfg = typeof _ListResidentsEp;
export type ListResidentsInputType = NonNullable<_ListResidentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListResidentsCfg['execute']>[0]['input'];
export type ListResidentsOutputType = Awaited<ReturnType<_ListResidentsCfg['execute']>>;
export const listResidents = createCaller<ListResidentsInputType, ListResidentsOutputType>('listResidents');

type _ListSchedulesCfg = typeof _ListSchedulesEp;
export type ListSchedulesInputType = NonNullable<_ListSchedulesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListSchedulesCfg['execute']>[0]['input'];
export type ListSchedulesOutputType = Awaited<ReturnType<_ListSchedulesCfg['execute']>>;
export const listSchedules = createCaller<ListSchedulesInputType, ListSchedulesOutputType>('listSchedules');

type _ListTasksCfg = typeof _ListTasksEp;
export type ListTasksInputType = NonNullable<_ListTasksCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListTasksCfg['execute']>[0]['input'];
export type ListTasksOutputType = Awaited<ReturnType<_ListTasksCfg['execute']>>;
export const listTasks = createCaller<ListTasksInputType, ListTasksOutputType>('listTasks');

type _ListTeamMembersCfg = typeof _ListTeamMembersEp;
export type ListTeamMembersInputType = NonNullable<_ListTeamMembersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListTeamMembersCfg['execute']>[0]['input'];
export type ListTeamMembersOutputType = Awaited<ReturnType<_ListTeamMembersCfg['execute']>>;
export const listTeamMembers = createCaller<ListTeamMembersInputType, ListTeamMembersOutputType>('listTeamMembers');

type _ListThreadsCfg = typeof _ListThreadsEp;
export type ListThreadsInputType = NonNullable<_ListThreadsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListThreadsCfg['execute']>[0]['input'];
export type ListThreadsOutputType = Awaited<ReturnType<_ListThreadsCfg['execute']>>;
export const listThreads = createCaller<ListThreadsInputType, ListThreadsOutputType>('listThreads');

type _ListTransactionsCfg = typeof _ListTransactionsEp;
export type ListTransactionsInputType = NonNullable<_ListTransactionsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListTransactionsCfg['execute']>[0]['input'];
export type ListTransactionsOutputType = Awaited<ReturnType<_ListTransactionsCfg['execute']>>;
export const listTransactions = createCaller<ListTransactionsInputType, ListTransactionsOutputType>('listTransactions');

type _ListVacanciesCfg = typeof _ListVacanciesEp;
export type ListVacanciesInputType = NonNullable<_ListVacanciesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListVacanciesCfg['execute']>[0]['input'];
export type ListVacanciesOutputType = Awaited<ReturnType<_ListVacanciesCfg['execute']>>;
export const listVacancies = createCaller<ListVacanciesInputType, ListVacanciesOutputType>('listVacancies');

type _ListVendorsCfg = typeof _ListVendorsEp;
export type ListVendorsInputType = NonNullable<_ListVendorsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListVendorsCfg['execute']>[0]['input'];
export type ListVendorsOutputType = Awaited<ReturnType<_ListVendorsCfg['execute']>>;
export const listVendors = createCaller<ListVendorsInputType, ListVendorsOutputType>('listVendors');

type _ListWorkOrdersCfg = typeof _ListWorkOrdersEp;
export type ListWorkOrdersInputType = NonNullable<_ListWorkOrdersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListWorkOrdersCfg['execute']>[0]['input'];
export type ListWorkOrdersOutputType = Awaited<ReturnType<_ListWorkOrdersCfg['execute']>>;
export const listWorkOrders = createCaller<ListWorkOrdersInputType, ListWorkOrdersOutputType>('listWorkOrders');

type _MarkThreadReadCfg = typeof _MarkThreadReadEp;
export type MarkThreadReadInputType = NonNullable<_MarkThreadReadCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MarkThreadReadCfg['execute']>[0]['input'];
export type MarkThreadReadOutputType = Awaited<ReturnType<_MarkThreadReadCfg['execute']>>;
export const markThreadRead = createCaller<MarkThreadReadInputType, MarkThreadReadOutputType>('markThreadRead');

type _MessageResidentCfg = typeof _MessageResidentEp;
export type MessageResidentInputType = NonNullable<_MessageResidentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MessageResidentCfg['execute']>[0]['input'];
export type MessageResidentOutputType = Awaited<ReturnType<_MessageResidentCfg['execute']>>;
export const messageResident = createCaller<MessageResidentInputType, MessageResidentOutputType>('messageResident');

type _MessageVendorCfg = typeof _MessageVendorEp;
export type MessageVendorInputType = NonNullable<_MessageVendorCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MessageVendorCfg['execute']>[0]['input'];
export type MessageVendorOutputType = Awaited<ReturnType<_MessageVendorCfg['execute']>>;
export const messageVendor = createCaller<MessageVendorInputType, MessageVendorOutputType>('messageVendor');

type _PayVendorBillsCfg = typeof _PayVendorBillsEp;
export type PayVendorBillsInputType = NonNullable<_PayVendorBillsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PayVendorBillsCfg['execute']>[0]['input'];
export type PayVendorBillsOutputType = Awaited<ReturnType<_PayVendorBillsCfg['execute']>>;
export const payVendorBills = createCaller<PayVendorBillsInputType, PayVendorBillsOutputType>('payVendorBills');

type _PostBankActivityCfg = typeof _PostBankActivityEp;
export type PostBankActivityInputType = NonNullable<_PostBankActivityCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PostBankActivityCfg['execute']>[0]['input'];
export type PostBankActivityOutputType = Awaited<ReturnType<_PostBankActivityCfg['execute']>>;
export const postBankActivity = createCaller<PostBankActivityInputType, PostBankActivityOutputType>('postBankActivity');

type _PostBulkChargesCfg = typeof _PostBulkChargesEp;
export type PostBulkChargesInputType = NonNullable<_PostBulkChargesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PostBulkChargesCfg['execute']>[0]['input'];
export type PostBulkChargesOutputType = Awaited<ReturnType<_PostBulkChargesCfg['execute']>>;
export const postBulkCharges = createCaller<PostBulkChargesInputType, PostBulkChargesOutputType>('postBulkCharges');

type _PostJournalCfg = typeof _PostJournalEp;
export type PostJournalInputType = NonNullable<_PostJournalCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PostJournalCfg['execute']>[0]['input'];
export type PostJournalOutputType = Awaited<ReturnType<_PostJournalCfg['execute']>>;
export const postJournal = createCaller<PostJournalInputType, PostJournalOutputType>('postJournal');

type _PostLeaseMoneyCfg = typeof _PostLeaseMoneyEp;
export type PostLeaseMoneyInputType = NonNullable<_PostLeaseMoneyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PostLeaseMoneyCfg['execute']>[0]['input'];
export type PostLeaseMoneyOutputType = Awaited<ReturnType<_PostLeaseMoneyCfg['execute']>>;
export const postLeaseMoney = createCaller<PostLeaseMoneyInputType, PostLeaseMoneyOutputType>('postLeaseMoney');

type _PostOwnerFundsCfg = typeof _PostOwnerFundsEp;
export type PostOwnerFundsInputType = NonNullable<_PostOwnerFundsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PostOwnerFundsCfg['execute']>[0]['input'];
export type PostOwnerFundsOutputType = Awaited<ReturnType<_PostOwnerFundsCfg['execute']>>;
export const postOwnerFunds = createCaller<PostOwnerFundsInputType, PostOwnerFundsOutputType>('postOwnerFunds');

type _PreviewAnnouncementCfg = typeof _PreviewAnnouncementEp;
export type PreviewAnnouncementInputType = NonNullable<_PreviewAnnouncementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PreviewAnnouncementCfg['execute']>[0]['input'];
export type PreviewAnnouncementOutputType = Awaited<ReturnType<_PreviewAnnouncementCfg['execute']>>;
export const previewAnnouncement = createCaller<PreviewAnnouncementInputType, PreviewAnnouncementOutputType>('previewAnnouncement');

type _PreviewMessageCfg = typeof _PreviewMessageEp;
export type PreviewMessageInputType = NonNullable<_PreviewMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_PreviewMessageCfg['execute']>[0]['input'];
export type PreviewMessageOutputType = Awaited<ReturnType<_PreviewMessageCfg['execute']>>;
export const previewMessage = createCaller<PreviewMessageInputType, PreviewMessageOutputType>('previewMessage');

type _ReplyToInquiryCfg = typeof _ReplyToInquiryEp;
export type ReplyToInquiryInputType = NonNullable<_ReplyToInquiryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReplyToInquiryCfg['execute']>[0]['input'];
export type ReplyToInquiryOutputType = Awaited<ReturnType<_ReplyToInquiryCfg['execute']>>;
export const replyToInquiry = createCaller<ReplyToInquiryInputType, ReplyToInquiryOutputType>('replyToInquiry');

type _ReportAgingCfg = typeof _ReportAgingEp;
export type ReportAgingInputType = NonNullable<_ReportAgingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportAgingCfg['execute']>[0]['input'];
export type ReportAgingOutputType = Awaited<ReturnType<_ReportAgingCfg['execute']>>;
export const reportAging = createCaller<ReportAgingInputType, ReportAgingOutputType>('reportAging');

type _ReportBalanceSheetCfg = typeof _ReportBalanceSheetEp;
export type ReportBalanceSheetInputType = NonNullable<_ReportBalanceSheetCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportBalanceSheetCfg['execute']>[0]['input'];
export type ReportBalanceSheetOutputType = Awaited<ReturnType<_ReportBalanceSheetCfg['execute']>>;
export const reportBalanceSheet = createCaller<ReportBalanceSheetInputType, ReportBalanceSheetOutputType>('reportBalanceSheet');

type _ReportCashFlowCfg = typeof _ReportCashFlowEp;
export type ReportCashFlowInputType = NonNullable<_ReportCashFlowCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportCashFlowCfg['execute']>[0]['input'];
export type ReportCashFlowOutputType = Awaited<ReturnType<_ReportCashFlowCfg['execute']>>;
export const reportCashFlow = createCaller<ReportCashFlowInputType, ReportCashFlowOutputType>('reportCashFlow');

type _ReportDepositsCfg = typeof _ReportDepositsEp;
export type ReportDepositsInputType = NonNullable<_ReportDepositsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportDepositsCfg['execute']>[0]['input'];
export type ReportDepositsOutputType = Awaited<ReturnType<_ReportDepositsCfg['execute']>>;
export const reportDeposits = createCaller<ReportDepositsInputType, ReportDepositsOutputType>('reportDeposits');

type _ReportExpirationsCfg = typeof _ReportExpirationsEp;
export type ReportExpirationsInputType = NonNullable<_ReportExpirationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportExpirationsCfg['execute']>[0]['input'];
export type ReportExpirationsOutputType = Awaited<ReturnType<_ReportExpirationsCfg['execute']>>;
export const reportExpirations = createCaller<ReportExpirationsInputType, ReportExpirationsOutputType>('reportExpirations');

type _ReportGeneralLedgerCfg = typeof _ReportGeneralLedgerEp;
export type ReportGeneralLedgerInputType = NonNullable<_ReportGeneralLedgerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportGeneralLedgerCfg['execute']>[0]['input'];
export type ReportGeneralLedgerOutputType = Awaited<ReturnType<_ReportGeneralLedgerCfg['execute']>>;
export const reportGeneralLedger = createCaller<ReportGeneralLedgerInputType, ReportGeneralLedgerOutputType>('reportGeneralLedger');

type _ReportIncomeStatementCfg = typeof _ReportIncomeStatementEp;
export type ReportIncomeStatementInputType = NonNullable<_ReportIncomeStatementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportIncomeStatementCfg['execute']>[0]['input'];
export type ReportIncomeStatementOutputType = Awaited<ReturnType<_ReportIncomeStatementCfg['execute']>>;
export const reportIncomeStatement = createCaller<ReportIncomeStatementInputType, ReportIncomeStatementOutputType>('reportIncomeStatement');

type _ReportLeasingFunnelCfg = typeof _ReportLeasingFunnelEp;
export type ReportLeasingFunnelInputType = NonNullable<_ReportLeasingFunnelCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportLeasingFunnelCfg['execute']>[0]['input'];
export type ReportLeasingFunnelOutputType = Awaited<ReturnType<_ReportLeasingFunnelCfg['execute']>>;
export const reportLeasingFunnel = createCaller<ReportLeasingFunnelInputType, ReportLeasingFunnelOutputType>('reportLeasingFunnel');

type _ReportOccupancyCfg = typeof _ReportOccupancyEp;
export type ReportOccupancyInputType = NonNullable<_ReportOccupancyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportOccupancyCfg['execute']>[0]['input'];
export type ReportOccupancyOutputType = Awaited<ReturnType<_ReportOccupancyCfg['execute']>>;
export const reportOccupancy = createCaller<ReportOccupancyInputType, ReportOccupancyOutputType>('reportOccupancy');

type _ReportOwnerStatementCfg = typeof _ReportOwnerStatementEp;
export type ReportOwnerStatementInputType = NonNullable<_ReportOwnerStatementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportOwnerStatementCfg['execute']>[0]['input'];
export type ReportOwnerStatementOutputType = Awaited<ReturnType<_ReportOwnerStatementCfg['execute']>>;
export const reportOwnerStatement = createCaller<ReportOwnerStatementInputType, ReportOwnerStatementOutputType>('reportOwnerStatement');

type _ReportPaymentsCfg = typeof _ReportPaymentsEp;
export type ReportPaymentsInputType = NonNullable<_ReportPaymentsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportPaymentsCfg['execute']>[0]['input'];
export type ReportPaymentsOutputType = Awaited<ReturnType<_ReportPaymentsCfg['execute']>>;
export const reportPayments = createCaller<ReportPaymentsInputType, ReportPaymentsOutputType>('reportPayments');

type _ReportPdfCfg = typeof _ReportPdfEp;
export type ReportPdfInputType = NonNullable<_ReportPdfCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportPdfCfg['execute']>[0]['input'];
export type ReportPdfOutputType = Awaited<ReturnType<_ReportPdfCfg['execute']>>;
export const reportPdf = createCaller<ReportPdfInputType, ReportPdfOutputType>('reportPdf');

type _ReportRentRollCfg = typeof _ReportRentRollEp;
export type ReportRentRollInputType = NonNullable<_ReportRentRollCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportRentRollCfg['execute']>[0]['input'];
export type ReportRentRollOutputType = Awaited<ReturnType<_ReportRentRollCfg['execute']>>;
export const reportRentRoll = createCaller<ReportRentRollInputType, ReportRentRollOutputType>('reportRentRoll');

type _ReportTrialBalanceCfg = typeof _ReportTrialBalanceEp;
export type ReportTrialBalanceInputType = NonNullable<_ReportTrialBalanceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportTrialBalanceCfg['execute']>[0]['input'];
export type ReportTrialBalanceOutputType = Awaited<ReturnType<_ReportTrialBalanceCfg['execute']>>;
export const reportTrialBalance = createCaller<ReportTrialBalanceInputType, ReportTrialBalanceOutputType>('reportTrialBalance');

type _ReportVacancyCfg = typeof _ReportVacancyEp;
export type ReportVacancyInputType = NonNullable<_ReportVacancyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportVacancyCfg['execute']>[0]['input'];
export type ReportVacancyOutputType = Awaited<ReturnType<_ReportVacancyCfg['execute']>>;
export const reportVacancy = createCaller<ReportVacancyInputType, ReportVacancyOutputType>('reportVacancy');

type _ReportVendorSpendCfg = typeof _ReportVendorSpendEp;
export type ReportVendorSpendInputType = NonNullable<_ReportVendorSpendCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportVendorSpendCfg['execute']>[0]['input'];
export type ReportVendorSpendOutputType = Awaited<ReturnType<_ReportVendorSpendCfg['execute']>>;
export const reportVendorSpend = createCaller<ReportVendorSpendInputType, ReportVendorSpendOutputType>('reportVendorSpend');

type _ReportWorkOrdersCfg = typeof _ReportWorkOrdersEp;
export type ReportWorkOrdersInputType = NonNullable<_ReportWorkOrdersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ReportWorkOrdersCfg['execute']>[0]['input'];
export type ReportWorkOrdersOutputType = Awaited<ReturnType<_ReportWorkOrdersCfg['execute']>>;
export const reportWorkOrders = createCaller<ReportWorkOrdersInputType, ReportWorkOrdersOutputType>('reportWorkOrders');

type _RunAutomationCfg = typeof _RunAutomationEp;
export type RunAutomationInputType = NonNullable<_RunAutomationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RunAutomationCfg['execute']>[0]['input'];
export type RunAutomationOutputType = Awaited<ReturnType<_RunAutomationCfg['execute']>>;
export const runAutomation = createCaller<RunAutomationInputType, RunAutomationOutputType>('runAutomation');

type _RunManagementFeesCfg = typeof _RunManagementFeesEp;
export type RunManagementFeesInputType = NonNullable<_RunManagementFeesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RunManagementFeesCfg['execute']>[0]['input'];
export type RunManagementFeesOutputType = Awaited<ReturnType<_RunManagementFeesCfg['execute']>>;
export const runManagementFees = createCaller<RunManagementFeesInputType, RunManagementFeesOutputType>('runManagementFees');

type _SaveAccountCfg = typeof _SaveAccountEp;
export type SaveAccountInputType = NonNullable<_SaveAccountCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveAccountCfg['execute']>[0]['input'];
export type SaveAccountOutputType = Awaited<ReturnType<_SaveAccountCfg['execute']>>;
export const saveAccount = createCaller<SaveAccountInputType, SaveAccountOutputType>('saveAccount');

type _SaveAnnouncementCfg = typeof _SaveAnnouncementEp;
export type SaveAnnouncementInputType = NonNullable<_SaveAnnouncementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveAnnouncementCfg['execute']>[0]['input'];
export type SaveAnnouncementOutputType = Awaited<ReturnType<_SaveAnnouncementCfg['execute']>>;
export const saveAnnouncement = createCaller<SaveAnnouncementInputType, SaveAnnouncementOutputType>('saveAnnouncement');

type _SaveDocumentCfg = typeof _SaveDocumentEp;
export type SaveDocumentInputType = NonNullable<_SaveDocumentCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveDocumentCfg['execute']>[0]['input'];
export type SaveDocumentOutputType = Awaited<ReturnType<_SaveDocumentCfg['execute']>>;
export const saveDocument = createCaller<SaveDocumentInputType, SaveDocumentOutputType>('saveDocument');

type _SaveEmailTemplateCfg = typeof _SaveEmailTemplateEp;
export type SaveEmailTemplateInputType = NonNullable<_SaveEmailTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveEmailTemplateCfg['execute']>[0]['input'];
export type SaveEmailTemplateOutputType = Awaited<ReturnType<_SaveEmailTemplateCfg['execute']>>;
export const saveEmailTemplate = createCaller<SaveEmailTemplateInputType, SaveEmailTemplateOutputType>('saveEmailTemplate');

type _SaveInquiryCfg = typeof _SaveInquiryEp;
export type SaveInquiryInputType = NonNullable<_SaveInquiryCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveInquiryCfg['execute']>[0]['input'];
export type SaveInquiryOutputType = Awaited<ReturnType<_SaveInquiryCfg['execute']>>;
export const saveInquiry = createCaller<SaveInquiryInputType, SaveInquiryOutputType>('saveInquiry');

type _SaveInspectionCfg = typeof _SaveInspectionEp;
export type SaveInspectionInputType = NonNullable<_SaveInspectionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveInspectionCfg['execute']>[0]['input'];
export type SaveInspectionOutputType = Awaited<ReturnType<_SaveInspectionCfg['execute']>>;
export const saveInspection = createCaller<SaveInspectionInputType, SaveInspectionOutputType>('saveInspection');

type _SaveListingCfg = typeof _SaveListingEp;
export type SaveListingInputType = NonNullable<_SaveListingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveListingCfg['execute']>[0]['input'];
export type SaveListingOutputType = Awaited<ReturnType<_SaveListingCfg['execute']>>;
export const saveListing = createCaller<SaveListingInputType, SaveListingOutputType>('saveListing');

type _SaveOwnerCfg = typeof _SaveOwnerEp;
export type SaveOwnerInputType = NonNullable<_SaveOwnerCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveOwnerCfg['execute']>[0]['input'];
export type SaveOwnerOutputType = Awaited<ReturnType<_SaveOwnerCfg['execute']>>;
export const saveOwner = createCaller<SaveOwnerInputType, SaveOwnerOutputType>('saveOwner');

type _SavePropertyCfg = typeof _SavePropertyEp;
export type SavePropertyInputType = NonNullable<_SavePropertyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SavePropertyCfg['execute']>[0]['input'];
export type SavePropertyOutputType = Awaited<ReturnType<_SavePropertyCfg['execute']>>;
export const saveProperty = createCaller<SavePropertyInputType, SavePropertyOutputType>('saveProperty');

type _SaveReconciliationCfg = typeof _SaveReconciliationEp;
export type SaveReconciliationInputType = NonNullable<_SaveReconciliationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveReconciliationCfg['execute']>[0]['input'];
export type SaveReconciliationOutputType = Awaited<ReturnType<_SaveReconciliationCfg['execute']>>;
export const saveReconciliation = createCaller<SaveReconciliationInputType, SaveReconciliationOutputType>('saveReconciliation');

type _SaveRecurringChargeCfg = typeof _SaveRecurringChargeEp;
export type SaveRecurringChargeInputType = NonNullable<_SaveRecurringChargeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveRecurringChargeCfg['execute']>[0]['input'];
export type SaveRecurringChargeOutputType = Awaited<ReturnType<_SaveRecurringChargeCfg['execute']>>;
export const saveRecurringCharge = createCaller<SaveRecurringChargeInputType, SaveRecurringChargeOutputType>('saveRecurringCharge');

type _SaveScheduleCfg = typeof _SaveScheduleEp;
export type SaveScheduleInputType = NonNullable<_SaveScheduleCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveScheduleCfg['execute']>[0]['input'];
export type SaveScheduleOutputType = Awaited<ReturnType<_SaveScheduleCfg['execute']>>;
export const saveSchedule = createCaller<SaveScheduleInputType, SaveScheduleOutputType>('saveSchedule');

type _SaveTaskCfg = typeof _SaveTaskEp;
export type SaveTaskInputType = NonNullable<_SaveTaskCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTaskCfg['execute']>[0]['input'];
export type SaveTaskOutputType = Awaited<ReturnType<_SaveTaskCfg['execute']>>;
export const saveTask = createCaller<SaveTaskInputType, SaveTaskOutputType>('saveTask');

type _SaveTenantCfg = typeof _SaveTenantEp;
export type SaveTenantInputType = NonNullable<_SaveTenantCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveTenantCfg['execute']>[0]['input'];
export type SaveTenantOutputType = Awaited<ReturnType<_SaveTenantCfg['execute']>>;
export const saveTenant = createCaller<SaveTenantInputType, SaveTenantOutputType>('saveTenant');

type _SaveUnitCfg = typeof _SaveUnitEp;
export type SaveUnitInputType = NonNullable<_SaveUnitCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveUnitCfg['execute']>[0]['input'];
export type SaveUnitOutputType = Awaited<ReturnType<_SaveUnitCfg['execute']>>;
export const saveUnit = createCaller<SaveUnitInputType, SaveUnitOutputType>('saveUnit');

type _SaveVendorCfg = typeof _SaveVendorEp;
export type SaveVendorInputType = NonNullable<_SaveVendorCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveVendorCfg['execute']>[0]['input'];
export type SaveVendorOutputType = Awaited<ReturnType<_SaveVendorCfg['execute']>>;
export const saveVendor = createCaller<SaveVendorInputType, SaveVendorOutputType>('saveVendor');

type _SaveViewCfg = typeof _SaveViewEp;
export type SaveViewInputType = NonNullable<_SaveViewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SaveViewCfg['execute']>[0]['input'];
export type SaveViewOutputType = Awaited<ReturnType<_SaveViewCfg['execute']>>;
export const saveView = createCaller<SaveViewInputType, SaveViewOutputType>('saveView');

type _ScheduleShowingCfg = typeof _ScheduleShowingEp;
export type ScheduleShowingInputType = NonNullable<_ScheduleShowingCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ScheduleShowingCfg['execute']>[0]['input'];
export type ScheduleShowingOutputType = Awaited<ReturnType<_ScheduleShowingCfg['execute']>>;
export const scheduleShowing = createCaller<ScheduleShowingInputType, ScheduleShowingOutputType>('scheduleShowing');

type _SearchCfg = typeof _SearchEp;
export type SearchInputType = NonNullable<_SearchCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SearchCfg['execute']>[0]['input'];
export type SearchOutputType = Awaited<ReturnType<_SearchCfg['execute']>>;
export const search = createCaller<SearchInputType, SearchOutputType>('search');

type _SeedWorkspaceCfg = typeof _SeedWorkspaceEp;
export type SeedWorkspaceInputType = NonNullable<_SeedWorkspaceCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SeedWorkspaceCfg['execute']>[0]['input'];
export type SeedWorkspaceOutputType = Awaited<ReturnType<_SeedWorkspaceCfg['execute']>>;
export const seedWorkspace = createCaller<SeedWorkspaceInputType, SeedWorkspaceOutputType>('seedWorkspace');

type _SendAnnouncementCfg = typeof _SendAnnouncementEp;
export type SendAnnouncementInputType = NonNullable<_SendAnnouncementCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendAnnouncementCfg['execute']>[0]['input'];
export type SendAnnouncementOutputType = Awaited<ReturnType<_SendAnnouncementCfg['execute']>>;
export const sendAnnouncement = createCaller<SendAnnouncementInputType, SendAnnouncementOutputType>('sendAnnouncement');

type _SendLateNoticesCfg = typeof _SendLateNoticesEp;
export type SendLateNoticesInputType = NonNullable<_SendLateNoticesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendLateNoticesCfg['execute']>[0]['input'];
export type SendLateNoticesOutputType = Awaited<ReturnType<_SendLateNoticesCfg['execute']>>;
export const sendLateNotices = createCaller<SendLateNoticesInputType, SendLateNoticesOutputType>('sendLateNotices');

type _SendMessagesCfg = typeof _SendMessagesEp;
export type SendMessagesInputType = NonNullable<_SendMessagesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendMessagesCfg['execute']>[0]['input'];
export type SendMessagesOutputType = Awaited<ReturnType<_SendMessagesCfg['execute']>>;
export const sendMessages = createCaller<SendMessagesInputType, SendMessagesOutputType>('sendMessages');

type _SendOwnerMessageCfg = typeof _SendOwnerMessageEp;
export type SendOwnerMessageInputType = NonNullable<_SendOwnerMessageCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendOwnerMessageCfg['execute']>[0]['input'];
export type SendOwnerMessageOutputType = Awaited<ReturnType<_SendOwnerMessageCfg['execute']>>;
export const sendOwnerMessage = createCaller<SendOwnerMessageInputType, SendOwnerMessageOutputType>('sendOwnerMessage');

type _SendScheduledAnnouncementsCfg = typeof _SendScheduledAnnouncementsEp;
export type SendScheduledAnnouncementsInputType = NonNullable<_SendScheduledAnnouncementsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendScheduledAnnouncementsCfg['execute']>[0]['input'];
export type SendScheduledAnnouncementsOutputType = Awaited<ReturnType<_SendScheduledAnnouncementsCfg['execute']>>;
export const sendScheduledAnnouncements = createCaller<SendScheduledAnnouncementsInputType, SendScheduledAnnouncementsOutputType>('sendScheduledAnnouncements');

type _SendTemplateTestCfg = typeof _SendTemplateTestEp;
export type SendTemplateTestInputType = NonNullable<_SendTemplateTestCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendTemplateTestCfg['execute']>[0]['input'];
export type SendTemplateTestOutputType = Awaited<ReturnType<_SendTemplateTestCfg['execute']>>;
export const sendTemplateTest = createCaller<SendTemplateTestInputType, SendTemplateTestOutputType>('sendTemplateTest');

type _SettleDepositCfg = typeof _SettleDepositEp;
export type SettleDepositInputType = NonNullable<_SettleDepositCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SettleDepositCfg['execute']>[0]['input'];
export type SettleDepositOutputType = Awaited<ReturnType<_SettleDepositCfg['execute']>>;
export const settleDeposit = createCaller<SettleDepositInputType, SettleDepositOutputType>('settleDeposit');

type _UpdateApplicationCfg = typeof _UpdateApplicationEp;
export type UpdateApplicationInputType = NonNullable<_UpdateApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateApplicationCfg['execute']>[0]['input'];
export type UpdateApplicationOutputType = Awaited<ReturnType<_UpdateApplicationCfg['execute']>>;
export const updateApplication = createCaller<UpdateApplicationInputType, UpdateApplicationOutputType>('updateApplication');

type _UpdateLeaseCfg = typeof _UpdateLeaseEp;
export type UpdateLeaseInputType = NonNullable<_UpdateLeaseCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateLeaseCfg['execute']>[0]['input'];
export type UpdateLeaseOutputType = Awaited<ReturnType<_UpdateLeaseCfg['execute']>>;
export const updateLease = createCaller<UpdateLeaseInputType, UpdateLeaseOutputType>('updateLease');

type _UpdateMyProfileCfg = typeof _UpdateMyProfileEp;
export type UpdateMyProfileInputType = NonNullable<_UpdateMyProfileCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateMyProfileCfg['execute']>[0]['input'];
export type UpdateMyProfileOutputType = Awaited<ReturnType<_UpdateMyProfileCfg['execute']>>;
export const updateMyProfile = createCaller<UpdateMyProfileInputType, UpdateMyProfileOutputType>('updateMyProfile');

type _UpdateNotificationsCfg = typeof _UpdateNotificationsEp;
export type UpdateNotificationsInputType = NonNullable<_UpdateNotificationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateNotificationsCfg['execute']>[0]['input'];
export type UpdateNotificationsOutputType = Awaited<ReturnType<_UpdateNotificationsCfg['execute']>>;
export const updateNotifications = createCaller<UpdateNotificationsInputType, UpdateNotificationsOutputType>('updateNotifications');

type _UpdateOrgSettingsCfg = typeof _UpdateOrgSettingsEp;
export type UpdateOrgSettingsInputType = NonNullable<_UpdateOrgSettingsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateOrgSettingsCfg['execute']>[0]['input'];
export type UpdateOrgSettingsOutputType = Awaited<ReturnType<_UpdateOrgSettingsCfg['execute']>>;
export const updateOrgSettings = createCaller<UpdateOrgSettingsInputType, UpdateOrgSettingsOutputType>('updateOrgSettings');

type _UpdateTasksCfg = typeof _UpdateTasksEp;
export type UpdateTasksInputType = NonNullable<_UpdateTasksCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateTasksCfg['execute']>[0]['input'];
export type UpdateTasksOutputType = Awaited<ReturnType<_UpdateTasksCfg['execute']>>;
export const updateTasks = createCaller<UpdateTasksInputType, UpdateTasksOutputType>('updateTasks');

type _UpdateTeamMemberCfg = typeof _UpdateTeamMemberEp;
export type UpdateTeamMemberInputType = NonNullable<_UpdateTeamMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateTeamMemberCfg['execute']>[0]['input'];
export type UpdateTeamMemberOutputType = Awaited<ReturnType<_UpdateTeamMemberCfg['execute']>>;
export const updateTeamMember = createCaller<UpdateTeamMemberInputType, UpdateTeamMemberOutputType>('updateTeamMember');

type _UpdateUnitsCfg = typeof _UpdateUnitsEp;
export type UpdateUnitsInputType = NonNullable<_UpdateUnitsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateUnitsCfg['execute']>[0]['input'];
export type UpdateUnitsOutputType = Awaited<ReturnType<_UpdateUnitsCfg['execute']>>;
export const updateUnits = createCaller<UpdateUnitsInputType, UpdateUnitsOutputType>('updateUnits');

type _UpdateWorkOrdersCfg = typeof _UpdateWorkOrdersEp;
export type UpdateWorkOrdersInputType = NonNullable<_UpdateWorkOrdersCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateWorkOrdersCfg['execute']>[0]['input'];
export type UpdateWorkOrdersOutputType = Awaited<ReturnType<_UpdateWorkOrdersCfg['execute']>>;
export const updateWorkOrders = createCaller<UpdateWorkOrdersInputType, UpdateWorkOrdersOutputType>('updateWorkOrders');

type _VoidLedgerTransactionCfg = typeof _VoidLedgerTransactionEp;
export type VoidLedgerTransactionInputType = NonNullable<_VoidLedgerTransactionCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_VoidLedgerTransactionCfg['execute']>[0]['input'];
export type VoidLedgerTransactionOutputType = Awaited<ReturnType<_VoidLedgerTransactionCfg['execute']>>;
export const voidLedgerTransaction = createCaller<VoidLedgerTransactionInputType, VoidLedgerTransactionOutputType>('voidLedgerTransaction');

type _WorkOrderMoneyCfg = typeof _WorkOrderMoneyEp;
export type WorkOrderMoneyInputType = NonNullable<_WorkOrderMoneyCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_WorkOrderMoneyCfg['execute']>[0]['input'];
export type WorkOrderMoneyOutputType = Awaited<ReturnType<_WorkOrderMoneyCfg['execute']>>;
export const workOrderMoney = createCaller<WorkOrderMoneyInputType, WorkOrderMoneyOutputType>('workOrderMoney');


export const api = {
  addApplicationMessage,
  addWorkOrderComment,
  aiListingDescription,
  aiTriageWorkOrder,
  bootstrap,
  clearDemoData,
  createBill,
  createLeaseStaff,
  createWorkOrder,
  decideApplication,
  generateScheduleNow,
  getAccountRegister,
  getAnnouncement,
  getApplication,
  getBanking,
  getChartBalances,
  getDashboard,
  getInquiry,
  getInspection,
  getLease,
  getLeaseLedger,
  getListing,
  getOrgSettings,
  getOwner,
  getOwnerFunds,
  getOwnerStatementStaff,
  getProperty,
  getPropertyFinancials,
  getReceivables,
  getReconciliation,
  getResident,
  getTask,
  getThread,
  getTransaction,
  getUnit,
  getVendor,
  getWorkOrder,
  inspectionReportPdf,
  inviteTeamMember,
  leaseLifecycle,
  listAnnouncements,
  listApplications,
  listBillPayments,
  listBills,
  listDocuments,
  listEmailTemplates,
  listInquiries,
  listInspections,
  listLeases,
  listListings,
  listNotifications,
  listOwnerTransactions,
  listOwners,
  listPayments,
  listProperties,
  listPropertyLeases,
  listResidents,
  listSchedules,
  listTasks,
  listTeamMembers,
  listThreads,
  listTransactions,
  listVacancies,
  listVendors,
  listWorkOrders,
  markThreadRead,
  messageResident,
  messageVendor,
  payVendorBills,
  postBankActivity,
  postBulkCharges,
  postJournal,
  postLeaseMoney,
  postOwnerFunds,
  previewAnnouncement,
  previewMessage,
  replyToInquiry,
  reportAging,
  reportBalanceSheet,
  reportCashFlow,
  reportDeposits,
  reportExpirations,
  reportGeneralLedger,
  reportIncomeStatement,
  reportLeasingFunnel,
  reportOccupancy,
  reportOwnerStatement,
  reportPayments,
  reportPdf,
  reportRentRoll,
  reportTrialBalance,
  reportVacancy,
  reportVendorSpend,
  reportWorkOrders,
  runAutomation,
  runManagementFees,
  saveAccount,
  saveAnnouncement,
  saveDocument,
  saveEmailTemplate,
  saveInquiry,
  saveInspection,
  saveListing,
  saveOwner,
  saveProperty,
  saveReconciliation,
  saveRecurringCharge,
  saveSchedule,
  saveTask,
  saveTenant,
  saveUnit,
  saveVendor,
  saveView,
  scheduleShowing,
  search,
  seedWorkspace,
  sendAnnouncement,
  sendLateNotices,
  sendMessages,
  sendOwnerMessage,
  sendScheduledAnnouncements,
  sendTemplateTest,
  settleDeposit,
  updateApplication,
  updateLease,
  updateMyProfile,
  updateNotifications,
  updateOrgSettings,
  updateTasks,
  updateTeamMember,
  updateUnits,
  updateWorkOrders,
  voidLedgerTransaction,
  workOrderMoney,
};
