// Auto-generated by zitejs generate from zite.config.json. Do not edit manually.
// Email SDK — sends through the Zite email gateway via the runtime bridge.
//
// Usage in endpoint files (src/api/*.ts):
//   import { Email } from 'zitejs/email';
//
// Always use 'zitejs/email' — never a relative path like '../../.zite/integrations/email'.
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
//   await Email.send({ to, subject, body: [{ type: 'text', content: '...' }] })
//     => { success: boolean; messageId: string }
//
//   RTL languages (Hebrew, Arabic): pass direction: 'rtl' — dir attributes
//   inside body text are stripped by the sanitizer and will not work.

import { createEmailClient } from 'zitejs/runtime';

export type {
  EmailBlock,
  SendEmailParams,
  SendEmailResult,
} from 'zitejs/runtime';

export const Email = createEmailClient('email-1');
