// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Settings" table, as it is read back. */
export type SettingsRecordType = {
  id: string;
  /** Primary field. "Organization Name" */
  organizationName?: string;
  legalName?: string;
  logoUrl?: string;
  address?: string;
  phone?: string;
  supportEmail?: string;
  websiteUrl?: string;
  emergencyPhone?: string;
  officeHours?: string;
  currency?: string;
  timezone?: string;
  brandColor?: string;
  /** "Rent Due Day". 0 decimal places, format: local (e.g. 1,000,000.50) */
  rentDueDay?: number;
  /** "Grace Period Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  gracePeriodDays?: number;
  lateFeeType?: "None" | "Flat" | "Percent" | string;
  /** "Late Fee Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  lateFeeAmount?: number;
  /** "Late Fee Percent". 2 decimal places, format: local (e.g. 1,000,000.50) */
  lateFeePercent?: number;
  /** "Late Fee Max". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  lateFeeMax?: number;
  /** "Charge Days Ahead". 0 decimal places, format: local (e.g. 1,000,000.50) */
  chargeDaysAhead?: number;
  /** "Rent Reminder Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  rentReminderDays?: number;
  /** "Renewal Notice Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  renewalNoticeDays?: number;
  /** "Management Fee Percent". 2 decimal places, format: local (e.g. 1,000,000.50) */
  managementFeePercent?: number;
  /** "Owner Approval Threshold". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  ownerApprovalThreshold?: number;
  /** "Application Fee". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  applicationFee?: number;
  /** "Income Multiple". 1 decimal places, format: local (e.g. 1,000,000.50) */
  incomeMultiple?: number;
  portalHeadline?: string;
  portalIntro?: string;
  paymentInstructions?: string;
  onlinePayments?: boolean;
  allowPartialPayments?: boolean;
  maintenanceRequests?: boolean;
  applicationsOpen?: boolean;
  emailSignature?: string;
  leaseTemplate?: string;
  defaultRole?: "Property Manager" | "Leasing Agent" | "Maintenance" | "Accountant" | string;
  portalUrl?: string;
  staffAppUrl?: string;
  /** "Seeded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  seededAt?: string;
  /** "Automation Ran At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  automationRanAt?: string;
  automationSummary?: string;
  seedStatus?: string;
};

/** What you may write when creating or updating a record in the "Settings" table. */
export type SettingsRecordInput = {
  organizationName: string | null;
  legalName: string | null;
  logoUrl: string | null;
  address: string | null;
  phone: string | null;
  supportEmail: string | null;
  websiteUrl: string | null;
  emergencyPhone: string | null;
  officeHours: string | null;
  currency: string | null;
  timezone: string | null;
  brandColor: string | null;
  rentDueDay: string | number | null;
  gracePeriodDays: string | number | null;
  lateFeeType: "None" | "Flat" | "Percent" | string | null;
  lateFeeAmount: string | number | null;
  lateFeePercent: string | number | null;
  lateFeeMax: string | number | null;
  chargeDaysAhead: string | number | null;
  rentReminderDays: string | number | null;
  renewalNoticeDays: string | number | null;
  managementFeePercent: string | number | null;
  ownerApprovalThreshold: string | number | null;
  applicationFee: string | number | null;
  incomeMultiple: string | number | null;
  portalHeadline: string | null;
  portalIntro: string | null;
  paymentInstructions: string | null;
  onlinePayments: string | boolean | null;
  allowPartialPayments: string | boolean | null;
  maintenanceRequests: string | boolean | null;
  applicationsOpen: string | boolean | null;
  emailSignature: string | null;
  leaseTemplate: string | null;
  defaultRole: "Property Manager" | "Leasing Agent" | "Maintenance" | "Accountant" | string | null;
  portalUrl: string | null;
  staffAppUrl: string | null;
  seededAt: string | Date | null;
  automationRanAt: string | Date | null;
  automationSummary: string | null;
  seedStatus: string | null;
};

/** A record in the "Members" table, as it is read back. */
export type MembersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  role?: "Admin" | "Property Manager" | "Leasing Agent" | "Maintenance" | "Accountant" | string;
  status?: "Active" | "Invited" | "Deactivated" | string;
  color?: string;
  avatarUrl?: string;
  title?: string;
  phone?: string;
  /** "Invited At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  invitedAt?: string;
  /** "Last Seen At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastSeenAt?: string;
};

/** What you may write when creating or updating a record in the "Members" table. */
export type MembersRecordInput = {
  name: string | null;
  email: string | null;
  role: "Admin" | "Property Manager" | "Leasing Agent" | "Maintenance" | "Accountant" | string | null;
  status: "Active" | "Invited" | "Deactivated" | string | null;
  color: string | null;
  avatarUrl: string | null;
  title: string | null;
  phone: string | null;
  invitedAt: string | Date | null;
  lastSeenAt: string | Date | null;
};

/** A record in the "Owners" table, as it is read back. */
export type OwnersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  ownerType?: "Individual" | "Company" | "Trust" | "Partnership" | string;
  contactName?: string;
  email?: string;
  phone?: string;
  mailingAddress?: string;
  taxIdLast4?: string;
  /** "Management Fee Percent". 2 decimal places, format: local (e.g. 1,000,000.50) */
  managementFeePercent?: number;
  distributionMethod?: "ACH" | "Check" | "Hold" | string;
  portalEnabled?: boolean;
  status?: "Active" | "Archived" | string;
  color?: string;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Owners" table. */
export type OwnersRecordInput = {
  name: string | null;
  ownerType: "Individual" | "Company" | "Trust" | "Partnership" | string | null;
  contactName: string | null;
  email: string | null;
  phone: string | null;
  mailingAddress: string | null;
  taxIdLast4: string | null;
  managementFeePercent: string | number | null;
  distributionMethod: "ACH" | "Check" | "Hold" | string | null;
  portalEnabled: string | boolean | null;
  status: "Active" | "Archived" | string | null;
  color: string | null;
  notes: string | null;
};

/** A record in the "Properties" table, as it is read back. */
export type PropertiesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  code?: string;
  propertyType?: "Single-family" | "Multifamily" | "Condo" | "Townhome" | "Commercial" | "Mixed-use" | string;
  status?: "Active" | "Inactive" | "Archived" | string;
  street?: string;
  city?: string;
  state?: string;
  postalCode?: string;
  ownerId?: string;
  managerId?: string;
  bankAccountId?: string;
  /** "Year Built". 0 decimal places, format: local (e.g. 1,000,000.50) */
  yearBuilt?: number;
  photoUrl?: string;
  description?: string;
  amenities?: string;
  /** "Management Fee Percent". 2 decimal places, format: local (e.g. 1,000,000.50) */
  managementFeePercent?: number;
  /** "Reserve Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  reserveAmount?: number;
  petPolicy?: string;
  parking?: string;
  /** "Acquired On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  acquiredOn?: string;
  color?: string;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Properties" table. */
export type PropertiesRecordInput = {
  name: string | null;
  code: string | null;
  propertyType: "Single-family" | "Multifamily" | "Condo" | "Townhome" | "Commercial" | "Mixed-use" | string | null;
  status: "Active" | "Inactive" | "Archived" | string | null;
  street: string | null;
  city: string | null;
  state: string | null;
  postalCode: string | null;
  ownerId: string | null;
  managerId: string | null;
  bankAccountId: string | null;
  yearBuilt: string | number | null;
  photoUrl: string | null;
  description: string | null;
  amenities: string | null;
  managementFeePercent: string | number | null;
  reserveAmount: string | number | null;
  petPolicy: string | null;
  parking: string | null;
  acquiredOn: string | Date | null;
  color: string | null;
  notes: string | null;
};

/** A record in the "Units" table, as it is read back. */
export type UnitsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  propertyId?: string;
  /** "Beds". 0 decimal places, format: local (e.g. 1,000,000.50) */
  beds?: number;
  /** "Baths". 1 decimal places, format: local (e.g. 1,000,000.50) */
  baths?: number;
  /** "Square Feet". 0 decimal places, format: local (e.g. 1,000,000.50) */
  squareFeet?: number;
  /** "Market Rent". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  marketRent?: number;
  /** "Deposit Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  depositAmount?: number;
  readiness?: "Ready" | "Make ready" | "Down" | "Off market" | string;
  floor?: string;
  unitType?: string;
  features?: string;
  photoUrls?: string;
  description?: string;
  /** "Available On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  availableOn?: string;
  archived?: boolean;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Units" table. */
export type UnitsRecordInput = {
  name: string | null;
  propertyId: string | null;
  beds: string | number | null;
  baths: string | number | null;
  squareFeet: string | number | null;
  marketRent: string | number | null;
  depositAmount: string | number | null;
  readiness: "Ready" | "Make ready" | "Down" | "Off market" | string | null;
  floor: string | null;
  unitType: string | null;
  features: string | null;
  photoUrls: string | null;
  description: string | null;
  availableOn: string | Date | null;
  archived: string | boolean | null;
  notes: string | null;
};

/** A record in the "Tenants" table, as it is read back. */
export type TenantsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  phone?: string;
  altPhone?: string;
  company?: string;
  emergencyContact?: string;
  emergencyPhone?: string;
  vehicles?: string;
  pets?: string;
  color?: string;
  /** "Portal Invited At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  portalInvitedAt?: string;
  /** "Portal Seen At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  portalSeenAt?: string;
  archived?: boolean;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Tenants" table. */
export type TenantsRecordInput = {
  name: string | null;
  email: string | null;
  phone: string | null;
  altPhone: string | null;
  company: string | null;
  emergencyContact: string | null;
  emergencyPhone: string | null;
  vehicles: string | null;
  pets: string | null;
  color: string | null;
  portalInvitedAt: string | Date | null;
  portalSeenAt: string | Date | null;
  archived: string | boolean | null;
  notes: string | null;
};

/** A record in the "Leases" table, as it is read back. */
export type LeasesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  /** "Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  number?: number;
  propertyId?: string;
  unitId?: string;
  status?: "Draft" | "Pending signature" | "Active" | "Ended" | "Canceled" | string;
  leaseType?: "Fixed term" | "Month-to-month" | string;
  /** "Start Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  startDate?: string;
  /** "End Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  endDate?: string;
  /** "Move In Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  moveInDate?: string;
  /** "Move Out Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  moveOutDate?: string;
  /** "Notice Given On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  noticeGivenOn?: string;
  /** "Rent". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  rent?: number;
  /** "Deposit". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  deposit?: number;
  /** "Rent Due Day". 0 decimal places, format: local (e.g. 1,000,000.50) */
  rentDueDay?: number;
  lateFeeExempt?: boolean;
  renewalStatus?: "None" | "Offered" | "Accepted" | "Declined" | string;
  /** "Renewal Rent". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  renewalRent?: number;
  /** "Renewal Term Months". 0 decimal places, format: local (e.g. 1,000,000.50) */
  renewalTermMonths?: number;
  /** "Renewal Offered At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  renewalOfferedAt?: string;
  /** "Renewal Expires On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  renewalExpiresOn?: string;
  /** "Renewal Responded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  renewalRespondedAt?: string;
  renewalLeaseId?: string;
  previousLeaseId?: string;
  applicationId?: string;
  terms?: string;
  /** "Sent For Signature At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sentForSignatureAt?: string;
  signatures?: string;
  /** "Signed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  signedAt?: string;
  /** "Countersigned At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  countersignedAt?: string;
  countersignedById?: string;
  documentUrl?: string;
  moveOutReason?: string;
  forwardingAddress?: string;
  /** "Deposit Settled At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  depositSettledAt?: string;
  createdById?: string;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Leases" table. */
export type LeasesRecordInput = {
  name: string | null;
  number: string | number | null;
  propertyId: string | null;
  unitId: string | null;
  status: "Draft" | "Pending signature" | "Active" | "Ended" | "Canceled" | string | null;
  leaseType: "Fixed term" | "Month-to-month" | string | null;
  startDate: string | Date | null;
  endDate: string | Date | null;
  moveInDate: string | Date | null;
  moveOutDate: string | Date | null;
  noticeGivenOn: string | Date | null;
  rent: string | number | null;
  deposit: string | number | null;
  rentDueDay: string | number | null;
  lateFeeExempt: string | boolean | null;
  renewalStatus: "None" | "Offered" | "Accepted" | "Declined" | string | null;
  renewalRent: string | number | null;
  renewalTermMonths: string | number | null;
  renewalOfferedAt: string | Date | null;
  renewalExpiresOn: string | Date | null;
  renewalRespondedAt: string | Date | null;
  renewalLeaseId: string | null;
  previousLeaseId: string | null;
  applicationId: string | null;
  terms: string | null;
  sentForSignatureAt: string | Date | null;
  signatures: string | null;
  signedAt: string | Date | null;
  countersignedAt: string | Date | null;
  countersignedById: string | null;
  documentUrl: string | null;
  moveOutReason: string | null;
  forwardingAddress: string | null;
  depositSettledAt: string | Date | null;
  createdById: string | null;
  notes: string | null;
};

/** A record in the "Lease Tenants" table, as it is read back. */
export type LeaseTenantsRecordType = {
  id: string;
  /** Primary field. "Lease Id" */
  leaseId?: string;
  tenantId?: string;
  role?: "Primary" | "Co-tenant" | "Occupant" | "Guarantor" | string;
  /** "Signed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  signedAt?: string;
};

/** What you may write when creating or updating a record in the "Lease Tenants" table. */
export type LeaseTenantsRecordInput = {
  leaseId: string | null;
  tenantId: string | null;
  role: "Primary" | "Co-tenant" | "Occupant" | "Guarantor" | string | null;
  signedAt: string | Date | null;
};

/** A record in the "Recurring Charges" table, as it is read back. */
export type RecurringChargesRecordType = {
  id: string;
  /** Primary field. "Description" */
  description?: string;
  leaseId?: string;
  accountId?: string;
  /** "Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  frequency?: "Monthly" | "Quarterly" | "Annually" | string;
  /** "Day Of Month". 0 decimal places, format: local (e.g. 1,000,000.50) */
  dayOfMonth?: number;
  /** "Start Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  startDate?: string;
  /** "End Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  endDate?: string;
  lastPostedPeriod?: string;
  active?: boolean;
};

/** What you may write when creating or updating a record in the "Recurring Charges" table. */
export type RecurringChargesRecordInput = {
  description: string | null;
  leaseId: string | null;
  accountId: string | null;
  amount: string | number | null;
  frequency: "Monthly" | "Quarterly" | "Annually" | string | null;
  dayOfMonth: string | number | null;
  startDate: string | Date | null;
  endDate: string | Date | null;
  lastPostedPeriod: string | null;
  active: string | boolean | null;
};

/** A record in the "Accounts" table, as it is read back. */
export type AccountsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  number?: string;
  accountType?: "Asset" | "Liability" | "Equity" | "Income" | "Expense" | string;
  subtype?: "Bank" | "Receivable" | "Other asset" | "Payable" | "Deposits held" | "Prepaid" | "Other liability" | "Owner equity" | "Contributions" | "Distributions" | "Operating income" | "Other income" | "Operating expense" | "Other expense" | string;
  systemKey?: string;
  description?: string;
  active?: boolean;
  tenantCharge?: boolean;
  billExpense?: boolean;
  bankName?: string;
  accountLast4?: string;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Accounts" table. */
export type AccountsRecordInput = {
  name: string | null;
  number: string | null;
  accountType: "Asset" | "Liability" | "Equity" | "Income" | "Expense" | string | null;
  subtype: "Bank" | "Receivable" | "Other asset" | "Payable" | "Deposits held" | "Prepaid" | "Other liability" | "Owner equity" | "Contributions" | "Distributions" | "Operating income" | "Other income" | "Operating expense" | "Other expense" | string | null;
  systemKey: string | null;
  description: string | null;
  active: string | boolean | null;
  tenantCharge: string | boolean | null;
  billExpense: string | boolean | null;
  bankName: string | null;
  accountLast4: string | null;
  position: string | number | null;
};

/** A record in the "Transactions" table, as it is read back. */
export type TransactionsRecordType = {
  id: string;
  /** Primary field. "Description" */
  description?: string;
  /** "Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  number?: number;
  kind?: "Charge" | "Payment" | "Credit" | "Refund" | "Deposit application" | "Bill" | "Bill payment" | "Expense" | "Owner contribution" | "Owner distribution" | "Management fee" | "Transfer" | "Journal entry" | string;
  /** "Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  date?: string;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  /** "Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  status?: "Posted" | "Void" | string;
  propertyId?: string;
  unitId?: string;
  leaseId?: string;
  tenantId?: string;
  vendorId?: string;
  ownerId?: string;
  workOrderId?: string;
  accountId?: string;
  bankAccountId?: string;
  paymentMethod?: "Cash" | "Check" | "ACH" | "Card" | "Money order" | "Online" | "Other" | string;
  reference?: string;
  source?: "Manual" | "Recurring" | "Late fee" | "Portal" | "Online payment" | "Work order" | "Move-out" | "Import" | "System" | string;
  period?: string;
  recurringChargeId?: string;
  onlinePaymentId?: string;
  attachmentUrl?: string;
  /** "Voided At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  voidedAt?: string;
  voidReason?: string;
  voidedById?: string;
  createdById?: string;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Transactions" table. */
export type TransactionsRecordInput = {
  description: string | null;
  number: string | number | null;
  kind: "Charge" | "Payment" | "Credit" | "Refund" | "Deposit application" | "Bill" | "Bill payment" | "Expense" | "Owner contribution" | "Owner distribution" | "Management fee" | "Transfer" | "Journal entry" | string | null;
  date: string | Date | null;
  dueDate: string | Date | null;
  amount: string | number | null;
  status: "Posted" | "Void" | string | null;
  propertyId: string | null;
  unitId: string | null;
  leaseId: string | null;
  tenantId: string | null;
  vendorId: string | null;
  ownerId: string | null;
  workOrderId: string | null;
  accountId: string | null;
  bankAccountId: string | null;
  paymentMethod: "Cash" | "Check" | "ACH" | "Card" | "Money order" | "Online" | "Other" | string | null;
  reference: string | null;
  source: "Manual" | "Recurring" | "Late fee" | "Portal" | "Online payment" | "Work order" | "Move-out" | "Import" | "System" | string | null;
  period: string | null;
  recurringChargeId: string | null;
  onlinePaymentId: string | null;
  attachmentUrl: string | null;
  voidedAt: string | Date | null;
  voidReason: string | null;
  voidedById: string | null;
  createdById: string | null;
  notes: string | null;
};

/** A record in the "Journal Lines" table, as it is read back. */
export type JournalLinesRecordType = {
  id: string;
  /** Primary field. "Memo" */
  memo?: string;
  transactionId?: string;
  /** "Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  date?: string;
  accountId?: string;
  propertyId?: string;
  unitId?: string;
  leaseId?: string;
  ownerId?: string;
  vendorId?: string;
  /** "Debit". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  debit?: number;
  /** "Credit". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  credit?: number;
  void?: boolean;
  /** "Cleared At". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  clearedAt?: string;
  reconciliationId?: string;
};

/** What you may write when creating or updating a record in the "Journal Lines" table. */
export type JournalLinesRecordInput = {
  memo: string | null;
  transactionId: string | null;
  date: string | Date | null;
  accountId: string | null;
  propertyId: string | null;
  unitId: string | null;
  leaseId: string | null;
  ownerId: string | null;
  vendorId: string | null;
  debit: string | number | null;
  credit: string | number | null;
  void: string | boolean | null;
  clearedAt: string | Date | null;
  reconciliationId: string | null;
};

/** A record in the "Allocations" table, as it is read back. */
export type AllocationsRecordType = {
  id: string;
  /** Primary field. "Payment Id" */
  paymentId?: string;
  chargeId?: string;
  /** "Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  /** "Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  date?: string;
  void?: boolean;
};

/** What you may write when creating or updating a record in the "Allocations" table. */
export type AllocationsRecordInput = {
  paymentId: string | null;
  chargeId: string | null;
  amount: string | number | null;
  date: string | Date | null;
  void: string | boolean | null;
};

/** A record in the "Reconciliations" table, as it is read back. */
export type ReconciliationsRecordType = {
  id: string;
  /** Primary field. "Statement Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  statementDate?: string;
  bankAccountId?: string;
  /** "Statement Balance". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  statementBalance?: number;
  /** "Cleared Balance". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  clearedBalance?: number;
  status?: "In progress" | "Completed" | string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  completedById?: string;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Reconciliations" table. */
export type ReconciliationsRecordInput = {
  statementDate: string | Date | null;
  bankAccountId: string | null;
  statementBalance: string | number | null;
  clearedBalance: string | number | null;
  status: "In progress" | "Completed" | string | null;
  completedAt: string | Date | null;
  completedById: string | null;
  notes: string | null;
};

/** A record in the "Vendors" table, as it is read back. */
export type VendorsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  trade?: "General" | "Plumbing" | "Electrical" | "HVAC" | "Appliance" | "Landscaping" | "Cleaning" | "Pest control" | "Roofing" | "Painting" | "Locksmith" | "Flooring" | "Utilities" | "Insurance" | "Other" | string;
  contactName?: string;
  email?: string;
  phone?: string;
  address?: string;
  taxIdLast4?: string;
  is1099?: boolean;
  w9OnFile?: boolean;
  /** "Insurance Expires On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  insuranceExpiresOn?: string;
  licenseNumber?: string;
  /** "Hourly Rate". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  hourlyRate?: number;
  /** "Rating". 1 decimal places, format: local (e.g. 1,000,000.50) */
  rating?: number;
  status?: "Active" | "Inactive" | string;
  portalEnabled?: boolean;
  defaultAccountId?: string;
  /** "Payment Terms Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  paymentTermsDays?: number;
  color?: string;
  notes?: string;
};

/** What you may write when creating or updating a record in the "Vendors" table. */
export type VendorsRecordInput = {
  name: string | null;
  trade: "General" | "Plumbing" | "Electrical" | "HVAC" | "Appliance" | "Landscaping" | "Cleaning" | "Pest control" | "Roofing" | "Painting" | "Locksmith" | "Flooring" | "Utilities" | "Insurance" | "Other" | string | null;
  contactName: string | null;
  email: string | null;
  phone: string | null;
  address: string | null;
  taxIdLast4: string | null;
  is1099: string | boolean | null;
  w9OnFile: string | boolean | null;
  insuranceExpiresOn: string | Date | null;
  licenseNumber: string | null;
  hourlyRate: string | number | null;
  rating: string | number | null;
  status: "Active" | "Inactive" | string | null;
  portalEnabled: string | boolean | null;
  defaultAccountId: string | null;
  paymentTermsDays: string | number | null;
  color: string | null;
  notes: string | null;
};

/** A record in the "Work Orders" table, as it is read back. */
export type WorkOrdersRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  /** "Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  number?: number;
  description?: string;
  propertyId?: string;
  unitId?: string;
  leaseId?: string;
  tenantId?: string;
  category?: "Plumbing" | "Electrical" | "HVAC" | "Appliance" | "Pest control" | "Locks & keys" | "Doors & windows" | "Flooring" | "Painting" | "Landscaping" | "Roofing" | "Cleaning" | "Safety" | "Turnover" | "General" | string;
  priority?: "Emergency" | "High" | "Normal" | "Low" | string;
  status?: "New" | "Scheduled" | "In progress" | "On hold" | "Completed" | "Canceled" | string;
  source?: "Portal" | "Staff" | "Phone" | "Email" | "Inspection" | "Recurring" | string;
  assigneeId?: string;
  vendorId?: string;
  /** "Scheduled For". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  scheduledFor?: string;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  /** "Started At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  startedAt?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  permissionToEnter?: boolean;
  entryNotes?: string;
  /** "Estimate Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  estimateAmount?: number;
  /** "Actual Cost". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  actualCost?: number;
  billId?: string;
  tenantChargeId?: string;
  ownerApproval?: "Not required" | "Pending" | "Approved" | "Declined" | string;
  ownerApprovalNote?: string;
  /** "Owner Responded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  ownerRespondedAt?: string;
  photos?: string;
  completionNotes?: string;
  /** "Tenant Rating". 0 decimal places, format: local (e.g. 1,000,000.50) */
  tenantRating?: number;
  tenantFeedback?: string;
  scheduleId?: string;
  inspectionId?: string;
  createdById?: string;
  /** "Last Activity At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActivityAt?: string;
  /** "Reported At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  reportedAt?: string;
};

/** What you may write when creating or updating a record in the "Work Orders" table. */
export type WorkOrdersRecordInput = {
  title: string | null;
  number: string | number | null;
  description: string | null;
  propertyId: string | null;
  unitId: string | null;
  leaseId: string | null;
  tenantId: string | null;
  category: "Plumbing" | "Electrical" | "HVAC" | "Appliance" | "Pest control" | "Locks & keys" | "Doors & windows" | "Flooring" | "Painting" | "Landscaping" | "Roofing" | "Cleaning" | "Safety" | "Turnover" | "General" | string | null;
  priority: "Emergency" | "High" | "Normal" | "Low" | string | null;
  status: "New" | "Scheduled" | "In progress" | "On hold" | "Completed" | "Canceled" | string | null;
  source: "Portal" | "Staff" | "Phone" | "Email" | "Inspection" | "Recurring" | string | null;
  assigneeId: string | null;
  vendorId: string | null;
  scheduledFor: string | Date | null;
  dueDate: string | Date | null;
  startedAt: string | Date | null;
  completedAt: string | Date | null;
  permissionToEnter: string | boolean | null;
  entryNotes: string | null;
  estimateAmount: string | number | null;
  actualCost: string | number | null;
  billId: string | null;
  tenantChargeId: string | null;
  ownerApproval: "Not required" | "Pending" | "Approved" | "Declined" | string | null;
  ownerApprovalNote: string | null;
  ownerRespondedAt: string | Date | null;
  photos: string | null;
  completionNotes: string | null;
  tenantRating: string | number | null;
  tenantFeedback: string | null;
  scheduleId: string | null;
  inspectionId: string | null;
  createdById: string | null;
  lastActivityAt: string | Date | null;
  reportedAt: string | Date | null;
};

/** A record in the "Maintenance Schedules" table, as it is read back. */
export type MaintenanceSchedulesRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  description?: string;
  propertyId?: string;
  unitId?: string;
  category?: string;
  priority?: "High" | "Normal" | "Low" | string;
  frequency?: "Monthly" | "Quarterly" | "Semiannually" | "Annually" | string;
  /** "Next Due On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  nextDueOn?: string;
  /** "Lead Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  leadDays?: number;
  vendorId?: string;
  assigneeId?: string;
  /** "Estimate Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  estimateAmount?: number;
  active?: boolean;
  /** "Last Generated On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  lastGeneratedOn?: string;
};

/** What you may write when creating or updating a record in the "Maintenance Schedules" table. */
export type MaintenanceSchedulesRecordInput = {
  title: string | null;
  description: string | null;
  propertyId: string | null;
  unitId: string | null;
  category: string | null;
  priority: "High" | "Normal" | "Low" | string | null;
  frequency: "Monthly" | "Quarterly" | "Semiannually" | "Annually" | string | null;
  nextDueOn: string | Date | null;
  leadDays: string | number | null;
  vendorId: string | null;
  assigneeId: string | null;
  estimateAmount: string | number | null;
  active: string | boolean | null;
  lastGeneratedOn: string | Date | null;
};

/** A record in the "Inspections" table, as it is read back. */
export type InspectionsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  propertyId?: string;
  unitId?: string;
  leaseId?: string;
  inspectionType?: "Move-in" | "Move-out" | "Routine" | "Annual" | "Drive-by" | "Pre-listing" | string;
  status?: "Scheduled" | "In progress" | "Completed" | "Canceled" | string;
  /** "Scheduled For". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  scheduledFor?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  inspectorId?: string;
  areas?: string;
  summary?: string;
  overallCondition?: "Excellent" | "Good" | "Fair" | "Poor" | string;
  sharedWithTenant?: boolean;
  /** "Tenant Acknowledged At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  tenantAcknowledgedAt?: string;
  reportUrl?: string;
};

/** What you may write when creating or updating a record in the "Inspections" table. */
export type InspectionsRecordInput = {
  title: string | null;
  propertyId: string | null;
  unitId: string | null;
  leaseId: string | null;
  inspectionType: "Move-in" | "Move-out" | "Routine" | "Annual" | "Drive-by" | "Pre-listing" | string | null;
  status: "Scheduled" | "In progress" | "Completed" | "Canceled" | string | null;
  scheduledFor: string | Date | null;
  completedAt: string | Date | null;
  inspectorId: string | null;
  areas: string | null;
  summary: string | null;
  overallCondition: "Excellent" | "Good" | "Fair" | "Poor" | string | null;
  sharedWithTenant: string | boolean | null;
  tenantAcknowledgedAt: string | Date | null;
  reportUrl: string | null;
};

/** A record in the "Listings" table, as it is read back. */
export type ListingsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  slug?: string;
  propertyId?: string;
  unitId?: string;
  status?: "Draft" | "Published" | "Paused" | "Leased" | string;
  /** "Rent". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  rent?: number;
  /** "Deposit". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  deposit?: number;
  /** "Available On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  availableOn?: string;
  description?: string;
  photos?: string;
  amenities?: string;
  leaseTerm?: string;
  petPolicy?: "No pets" | "Cats only" | "Dogs only" | "Cats and dogs" | "Case by case" | string;
  /** "Application Fee". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  applicationFee?: number;
  showingInstructions?: string;
  contactMemberId?: string;
  /** "Published At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  publishedAt?: string;
  /** "Views". 0 decimal places, format: local (e.g. 1,000,000.50) */
  views?: number;
};

/** What you may write when creating or updating a record in the "Listings" table. */
export type ListingsRecordInput = {
  title: string | null;
  slug: string | null;
  propertyId: string | null;
  unitId: string | null;
  status: "Draft" | "Published" | "Paused" | "Leased" | string | null;
  rent: string | number | null;
  deposit: string | number | null;
  availableOn: string | Date | null;
  description: string | null;
  photos: string | null;
  amenities: string | null;
  leaseTerm: string | null;
  petPolicy: "No pets" | "Cats only" | "Dogs only" | "Cats and dogs" | "Case by case" | string | null;
  applicationFee: string | number | null;
  showingInstructions: string | null;
  contactMemberId: string | null;
  publishedAt: string | Date | null;
  views: string | number | null;
};

/** A record in the "Inquiries" table, as it is read back. */
export type InquiriesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  phone?: string;
  message?: string;
  listingId?: string;
  propertyId?: string;
  unitId?: string;
  status?: "New" | "Contacted" | "Showing scheduled" | "Applied" | "Closed" | string;
  source?: "Portal" | "Phone" | "Email" | "Walk-in" | "Listing site" | "Referral" | string;
  /** "Showing At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  showingAt?: string;
  /** "Desired Move In". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  desiredMoveIn?: string;
  assigneeId?: string;
  applicationId?: string;
  /** "Last Contacted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastContactedAt?: string;
  notes?: string;
  /** "Received At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  receivedAt?: string;
};

/** What you may write when creating or updating a record in the "Inquiries" table. */
export type InquiriesRecordInput = {
  name: string | null;
  email: string | null;
  phone: string | null;
  message: string | null;
  listingId: string | null;
  propertyId: string | null;
  unitId: string | null;
  status: "New" | "Contacted" | "Showing scheduled" | "Applied" | "Closed" | string | null;
  source: "Portal" | "Phone" | "Email" | "Walk-in" | "Listing site" | "Referral" | string | null;
  showingAt: string | Date | null;
  desiredMoveIn: string | Date | null;
  assigneeId: string | null;
  applicationId: string | null;
  lastContactedAt: string | Date | null;
  notes: string | null;
  receivedAt: string | Date | null;
};

/** A record in the "Applications" table, as it is read back. */
export type ApplicationsRecordType = {
  id: string;
  /** Primary field. "Applicant Name" */
  applicantName?: string;
  /** "Number". 0 decimal places, format: local (e.g. 1,000,000.50) */
  number?: number;
  listingId?: string;
  propertyId?: string;
  unitId?: string;
  status?: "Draft" | "Submitted" | "Screening" | "Approved" | "Denied" | "Withdrawn" | "Leased" | string;
  email?: string;
  phone?: string;
  portalEmail?: string;
  /** "Desired Move In". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  desiredMoveIn?: string;
  /** "Monthly Income". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  monthlyIncome?: number;
  employer?: string;
  jobTitle?: string;
  /** "Employment Months". 0 decimal places, format: local (e.g. 1,000,000.50) */
  employmentMonths?: number;
  currentAddress?: string;
  /** "Current Rent". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  currentRent?: number;
  currentLandlord?: string;
  landlordPhone?: string;
  /** "Residence Months". 0 decimal places, format: local (e.g. 1,000,000.50) */
  residenceMonths?: number;
  reasonForMoving?: string;
  /** "Occupants". 0 decimal places, format: local (e.g. 1,000,000.50) */
  occupants?: number;
  pets?: string;
  vehicles?: string;
  priorEviction?: boolean;
  coApplicants?: string;
  details?: string;
  screening?: string;
  screeningNotes?: string;
  /** "Consent At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  consentAt?: string;
  signature?: string;
  /** "Fee Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  feeAmount?: number;
  /** "Fee Paid At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  feePaidAt?: string;
  decisionReason?: string;
  decidedById?: string;
  /** "Decided At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  decidedAt?: string;
  /** "Submitted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  submittedAt?: string;
  source?: "Portal" | "Staff" | "Walk-in" | "Listing site" | "Referral" | string;
  assigneeId?: string;
  leaseId?: string;
  inquiryId?: string;
  /** "Last Activity At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  lastActivityAt?: string;
};

/** What you may write when creating or updating a record in the "Applications" table. */
export type ApplicationsRecordInput = {
  applicantName: string | null;
  number: string | number | null;
  listingId: string | null;
  propertyId: string | null;
  unitId: string | null;
  status: "Draft" | "Submitted" | "Screening" | "Approved" | "Denied" | "Withdrawn" | "Leased" | string | null;
  email: string | null;
  phone: string | null;
  portalEmail: string | null;
  desiredMoveIn: string | Date | null;
  monthlyIncome: string | number | null;
  employer: string | null;
  jobTitle: string | null;
  employmentMonths: string | number | null;
  currentAddress: string | null;
  currentRent: string | number | null;
  currentLandlord: string | null;
  landlordPhone: string | null;
  residenceMonths: string | number | null;
  reasonForMoving: string | null;
  occupants: string | number | null;
  pets: string | null;
  vehicles: string | null;
  priorEviction: string | boolean | null;
  coApplicants: string | null;
  details: string | null;
  screening: string | null;
  screeningNotes: string | null;
  consentAt: string | Date | null;
  signature: string | null;
  feeAmount: string | number | null;
  feePaidAt: string | Date | null;
  decisionReason: string | null;
  decidedById: string | null;
  decidedAt: string | Date | null;
  submittedAt: string | Date | null;
  source: "Portal" | "Staff" | "Walk-in" | "Listing site" | "Referral" | string | null;
  assigneeId: string | null;
  leaseId: string | null;
  inquiryId: string | null;
  lastActivityAt: string | Date | null;
};

/** A record in the "Messages" table, as it is read back. */
export type MessagesRecordType = {
  id: string;
  /** Primary field. "Subject" */
  subject?: string;
  body?: string;
  thread?: string;
  direction?: "Inbound" | "Outbound" | "Internal" | string;
  channel?: "Email" | "Portal" | "Note" | string;
  tenantId?: string;
  ownerId?: string;
  vendorId?: string;
  applicationId?: string;
  leaseId?: string;
  workOrderId?: string;
  propertyId?: string;
  announcementId?: string;
  senderMemberId?: string;
  senderName?: string;
  delivery?: "Sent" | "Failed" | "Portal only" | "Received" | string;
  templateId?: string;
  attachments?: string;
  /** "Read At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  readAt?: string;
  /** "Sent At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sentAt?: string;
};

/** What you may write when creating or updating a record in the "Messages" table. */
export type MessagesRecordInput = {
  subject: string | null;
  body: string | null;
  thread: string | null;
  direction: "Inbound" | "Outbound" | "Internal" | string | null;
  channel: "Email" | "Portal" | "Note" | string | null;
  tenantId: string | null;
  ownerId: string | null;
  vendorId: string | null;
  applicationId: string | null;
  leaseId: string | null;
  workOrderId: string | null;
  propertyId: string | null;
  announcementId: string | null;
  senderMemberId: string | null;
  senderName: string | null;
  delivery: "Sent" | "Failed" | "Portal only" | "Received" | string | null;
  templateId: string | null;
  attachments: string | null;
  readAt: string | Date | null;
  sentAt: string | Date | null;
};

/** A record in the "Announcements" table, as it is read back. */
export type AnnouncementsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  body?: string;
  audience?: "All residents" | "Selected properties" | "Owners" | "Vendors" | string;
  propertyIds?: string;
  channel?: "Email and portal" | "Portal only" | string;
  status?: "Draft" | "Sent" | string;
  /** "Sent At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sentAt?: string;
  sentById?: string;
  /** "Recipient Count". 0 decimal places, format: local (e.g. 1,000,000.50) */
  recipientCount?: number;
  /** "Pinned Until". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  pinnedUntil?: string;
};

/** What you may write when creating or updating a record in the "Announcements" table. */
export type AnnouncementsRecordInput = {
  title: string | null;
  body: string | null;
  audience: "All residents" | "Selected properties" | "Owners" | "Vendors" | string | null;
  propertyIds: string | null;
  channel: "Email and portal" | "Portal only" | string | null;
  status: "Draft" | "Sent" | string | null;
  sentAt: string | Date | null;
  sentById: string | null;
  recipientCount: string | number | null;
  pinnedUntil: string | Date | null;
};

/** A record in the "Documents" table, as it is read back. */
export type DocumentsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  url?: string;
  category?: "Lease" | "Addendum" | "Notice" | "Insurance" | "Inspection" | "Statement" | "Invoice" | "Receipt" | "Photo" | "Identification" | "Other" | string;
  propertyId?: string;
  unitId?: string;
  leaseId?: string;
  tenantId?: string;
  ownerId?: string;
  vendorId?: string;
  workOrderId?: string;
  applicationId?: string;
  sharedWithTenant?: boolean;
  sharedWithOwner?: boolean;
  uploadedById?: string;
  uploadedByName?: string;
  /** "Size". 0 decimal places, format: local (e.g. 1,000,000.50) */
  size?: number;
  mimeType?: string;
  /** "Expires On". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  expiresOn?: string;
  notes?: string;
  /** "Uploaded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  uploadedAt?: string;
};

/** What you may write when creating or updating a record in the "Documents" table. */
export type DocumentsRecordInput = {
  name: string | null;
  url: string | null;
  category: "Lease" | "Addendum" | "Notice" | "Insurance" | "Inspection" | "Statement" | "Invoice" | "Receipt" | "Photo" | "Identification" | "Other" | string | null;
  propertyId: string | null;
  unitId: string | null;
  leaseId: string | null;
  tenantId: string | null;
  ownerId: string | null;
  vendorId: string | null;
  workOrderId: string | null;
  applicationId: string | null;
  sharedWithTenant: string | boolean | null;
  sharedWithOwner: string | boolean | null;
  uploadedById: string | null;
  uploadedByName: string | null;
  size: string | number | null;
  mimeType: string | null;
  expiresOn: string | Date | null;
  notes: string | null;
  uploadedAt: string | Date | null;
};

/** A record in the "Tasks" table, as it is read back. */
export type TasksRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  description?: string;
  status?: "To do" | "In progress" | "Done" | "Canceled" | string;
  priority?: "Urgent" | "High" | "Normal" | "Low" | string;
  category?: "General" | "Leasing" | "Renewal" | "Move-in" | "Move-out" | "Maintenance" | "Inspection" | "Accounting" | "Compliance" | string;
  /** "Due Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  dueDate?: string;
  assigneeId?: string;
  propertyId?: string;
  unitId?: string;
  leaseId?: string;
  tenantId?: string;
  ownerId?: string;
  vendorId?: string;
  workOrderId?: string;
  applicationId?: string;
  createdById?: string;
  /** "Completed At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  completedAt?: string;
  systemKey?: string;
  /** "Opened At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  openedAt?: string;
};

/** What you may write when creating or updating a record in the "Tasks" table. */
export type TasksRecordInput = {
  title: string | null;
  description: string | null;
  status: "To do" | "In progress" | "Done" | "Canceled" | string | null;
  priority: "Urgent" | "High" | "Normal" | "Low" | string | null;
  category: "General" | "Leasing" | "Renewal" | "Move-in" | "Move-out" | "Maintenance" | "Inspection" | "Accounting" | "Compliance" | string | null;
  dueDate: string | Date | null;
  assigneeId: string | null;
  propertyId: string | null;
  unitId: string | null;
  leaseId: string | null;
  tenantId: string | null;
  ownerId: string | null;
  vendorId: string | null;
  workOrderId: string | null;
  applicationId: string | null;
  createdById: string | null;
  completedAt: string | Date | null;
  systemKey: string | null;
  openedAt: string | Date | null;
};

/** A record in the "Notifications" table, as it is read back. */
export type NotificationsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  body?: string;
  memberId?: string;
  kind?: string;
  link?: string;
  entityType?: string;
  entityId?: string;
  actorId?: string;
  actorName?: string;
  /** "Read At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  readAt?: string;
  /** "Archived At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  archivedAt?: string;
  /** "Snoozed Until". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  snoozedUntil?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
};

/** What you may write when creating or updating a record in the "Notifications" table. */
export type NotificationsRecordInput = {
  title: string | null;
  body: string | null;
  memberId: string | null;
  kind: string | null;
  link: string | null;
  entityType: string | null;
  entityId: string | null;
  actorId: string | null;
  actorName: string | null;
  readAt: string | Date | null;
  archivedAt: string | Date | null;
  snoozedUntil: string | Date | null;
  occurredAt: string | Date | null;
};

/** A record in the "Activity" table, as it is read back. */
export type ActivityRecordType = {
  id: string;
  /** Primary field. "Summary" */
  summary?: string;
  entityType?: string;
  entityId?: string;
  action?: string;
  actorId?: string;
  actorName?: string;
  data?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
  propertyId?: string;
  unitId?: string;
  leaseId?: string;
  tenantId?: string;
  ownerId?: string;
  vendorId?: string;
  workOrderId?: string;
  applicationId?: string;
};

/** What you may write when creating or updating a record in the "Activity" table. */
export type ActivityRecordInput = {
  summary: string | null;
  entityType: string | null;
  entityId: string | null;
  action: string | null;
  actorId: string | null;
  actorName: string | null;
  data: string | null;
  occurredAt: string | Date | null;
  propertyId: string | null;
  unitId: string | null;
  leaseId: string | null;
  tenantId: string | null;
  ownerId: string | null;
  vendorId: string | null;
  workOrderId: string | null;
  applicationId: string | null;
};

/** A record in the "Email Templates" table, as it is read back. */
export type EmailTemplatesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  trigger?: "Manual" | "Rent reminder" | "Payment receipt" | "Late notice" | "Lease expiring" | "Renewal offer" | "Signature request" | "Welcome" | "Move-out" | "Application received" | "Application approved" | "Application denied" | "Work order received" | "Work order scheduled" | "Work order completed" | "Vendor assigned" | "Owner statement" | "Owner approval" | string;
  audience?: "Tenant" | "Applicant" | "Owner" | "Vendor" | string;
  subject?: string;
  body?: string;
  enabled?: boolean;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Email Templates" table. */
export type EmailTemplatesRecordInput = {
  name: string | null;
  trigger: "Manual" | "Rent reminder" | "Payment receipt" | "Late notice" | "Lease expiring" | "Renewal offer" | "Signature request" | "Welcome" | "Move-out" | "Application received" | "Application approved" | "Application denied" | "Work order received" | "Work order scheduled" | "Work order completed" | "Vendor assigned" | "Owner statement" | "Owner approval" | string | null;
  audience: "Tenant" | "Applicant" | "Owner" | "Vendor" | string | null;
  subject: string | null;
  body: string | null;
  enabled: string | boolean | null;
  position: string | number | null;
};

/** A record in the "Views" table, as it is read back. */
export type ViewsRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  scope?: string;
  config?: string;
  ownerId?: string;
  shared?: boolean;
  /** "Position". 0 decimal places, format: local (e.g. 1,000,000.50) */
  position?: number;
};

/** What you may write when creating or updating a record in the "Views" table. */
export type ViewsRecordInput = {
  name: string | null;
  scope: string | null;
  config: string | null;
  ownerId: string | null;
  shared: string | boolean | null;
  position: string | number | null;
};

/** A record in the "Online Payments" table, as it is read back. */
export type OnlinePaymentsRecordType = {
  id: string;
  /** Primary field. "Intent Id" */
  intentId?: string;
  leaseId?: string;
  tenantId?: string;
  applicationId?: string;
  purpose?: "Rent" | "Application fee" | string;
  /** "Amount". Value is a raw number; display as currency with symbol "$", 2 decimal places, format: local (e.g. 1,000,000.50) */
  amount?: number;
  status?: "Pending" | "Processing" | "Succeeded" | "Failed" | "Canceled" | string;
  method?: string;
  transactionId?: string;
  payerEmail?: string;
  error?: string;
  /** "Settled At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  settledAt?: string;
};

/** What you may write when creating or updating a record in the "Online Payments" table. */
export type OnlinePaymentsRecordInput = {
  intentId: string | null;
  leaseId: string | null;
  tenantId: string | null;
  applicationId: string | null;
  purpose: "Rent" | "Application fee" | string | null;
  amount: string | number | null;
  status: "Pending" | "Processing" | "Succeeded" | "Failed" | "Canceled" | string | null;
  method: string | null;
  transactionId: string | null;
  payerEmail: string | null;
  error: string | null;
  settledAt: string | Date | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  settings: createTableClient<SettingsRecordType, SettingsRecordInput>('Settings'), // "Settings"
  members: createTableClient<MembersRecordType, MembersRecordInput>('Members'), // "Members"
  owners: createTableClient<OwnersRecordType, OwnersRecordInput>('Owners'), // "Owners"
  properties: createTableClient<PropertiesRecordType, PropertiesRecordInput>('Properties'), // "Properties"
  units: createTableClient<UnitsRecordType, UnitsRecordInput>('Units'), // "Units"
  tenants: createTableClient<TenantsRecordType, TenantsRecordInput>('Tenants'), // "Tenants"
  leases: createTableClient<LeasesRecordType, LeasesRecordInput>('Leases'), // "Leases"
  leaseTenants: createTableClient<LeaseTenantsRecordType, LeaseTenantsRecordInput>('LeaseTenants'), // "Lease Tenants"
  recurringCharges: createTableClient<RecurringChargesRecordType, RecurringChargesRecordInput>('RecurringCharges'), // "Recurring Charges"
  accounts: createTableClient<AccountsRecordType, AccountsRecordInput>('Accounts'), // "Accounts"
  transactions: createTableClient<TransactionsRecordType, TransactionsRecordInput>('Transactions'), // "Transactions"
  journalLines: createTableClient<JournalLinesRecordType, JournalLinesRecordInput>('JournalLines'), // "Journal Lines"
  allocations: createTableClient<AllocationsRecordType, AllocationsRecordInput>('Allocations'), // "Allocations"
  reconciliations: createTableClient<ReconciliationsRecordType, ReconciliationsRecordInput>('Reconciliations'), // "Reconciliations"
  vendors: createTableClient<VendorsRecordType, VendorsRecordInput>('Vendors'), // "Vendors"
  workOrders: createTableClient<WorkOrdersRecordType, WorkOrdersRecordInput>('WorkOrders'), // "Work Orders"
  maintenanceSchedules: createTableClient<MaintenanceSchedulesRecordType, MaintenanceSchedulesRecordInput>('MaintenanceSchedules'), // "Maintenance Schedules"
  inspections: createTableClient<InspectionsRecordType, InspectionsRecordInput>('Inspections'), // "Inspections"
  listings: createTableClient<ListingsRecordType, ListingsRecordInput>('Listings'), // "Listings"
  inquiries: createTableClient<InquiriesRecordType, InquiriesRecordInput>('Inquiries'), // "Inquiries"
  applications: createTableClient<ApplicationsRecordType, ApplicationsRecordInput>('Applications'), // "Applications"
  messages: createTableClient<MessagesRecordType, MessagesRecordInput>('Messages'), // "Messages"
  announcements: createTableClient<AnnouncementsRecordType, AnnouncementsRecordInput>('Announcements'), // "Announcements"
  documents: createTableClient<DocumentsRecordType, DocumentsRecordInput>('Documents'), // "Documents"
  tasks: createTableClient<TasksRecordType, TasksRecordInput>('Tasks'), // "Tasks"
  notifications: createTableClient<NotificationsRecordType, NotificationsRecordInput>('Notifications'), // "Notifications"
  activity: createTableClient<ActivityRecordType, ActivityRecordInput>('Activity'), // "Activity"
  emailTemplates: createTableClient<EmailTemplatesRecordType, EmailTemplatesRecordInput>('EmailTemplates'), // "Email Templates"
  views: createTableClient<ViewsRecordType, ViewsRecordInput>('Views'), // "Views"
  onlinePayments: createTableClient<OnlinePaymentsRecordType, OnlinePaymentsRecordInput>('OnlinePayments'), // "Online Payments"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
